### ISSUE TITLE
Add reaver and other WiFi cracking tools to Hijacker

### ISSUE THREAD

**Issue by AutinDroid** [chrisk44/Hijacker#1]
I have been using reaver on my Nexus 5, and it works beautifully with nexmon! It is already very good, but it could be improved further with other wifi tools like reaver and wifite. This would make wireless cracking more efficient and would provide a better solution to cracking than using a dongle with nethunter's chroot. I would also like to thank you for your hard work. Keep up the good work!

**Comment by chrisk44** [comment]
I will add some more tools such as besside-ng and yes reaver... Just need to make it stable enough with these tools first... Are you using that reaver android app or just the binary in a terminal?

**Comment by AutinDroid** [comment]
I use chroot with a dongle. I am not aware of any reaver android binaries, and I have not tried tovcreat scripts for the app (reaver-gui).

**Comment by chrisk44** [comment]
Oh ok. I asked because I tried reaver-gui but didn't work with those scripts it needed and whatnot...

**Comment by AutinDroid** [comment]
I will see if I can make the reaver GUI work properly work. I would also like to help the project and maybe help with the interface like icons and other stuff (I'm not much of a coder).

**Comment by chrisk44** [comment]
If you could test it and report that would be a great help...

**Comment by AutinDroid** [comment]
Sure! I would love to help

**Comment by AutinDroid** [comment]
Also, it would be nice if a dictionary or John the ripper would be included in the app to crack the cap file.

**Comment by chrisk44** [comment]
I will include a dictionary or let the user use one, and also auto cracking of a wep key, but as I said, it need to be much more stable to start implementing new features... Are you using it?

**Comment by AutinDroid** [comment]
I haven't tried to crack the .cap file yet, but I can say that the app can capture handshakes very well. I will try to build a version of this with an improved GUI.

**Comment by chrisk44** [comment]
I will change the gui to use fragments for every action and swap using a sidebar... not sure when it will be ready though...

**Comment by NetviperZ** [comment]
Hello! I want to thank you infinitely for your efforts, I just tested it and it works perfectly, however mdk3 seem not working properly or not at all..it will be indeed interesting to add stuffs like wifite/reaver  and why not a small wpa dico for more fun ! i have arrived finally to run nexmon in nethunter's chroot without dongle and monitor mode and other wifitools like wifite & reaver seems working properly (on a modified CM 14.1 nougat ).

**Comment by chrisk44** [comment]
Hi. Be aware that the mdk3 binary that comes with the nexmon app is faulty and indeed doesn't work. You can use the install tools option from the settings, which will install everything (it will overwrite existing tools). If airodump and aireplay are working for you, then it's probably the mdk3 binary that causes a problem.

**Comment by NetviperZ** [comment]
hi just tested your last version v0.11-beta and noticed that mdk attacks from the menu has been removed, so i reinstalled version v0.10-beta and after adding /su/xbin/mdk3 on "MDK3 absolute path" on the setting the problem seems be fixed! hope that help soemone

**Comment by chrisk44** [comment]
Yes, it has been removed from the toolbar menu, it is now accessible via the navigation drawer. Slide to the right from the left egde of your screen to unveil it and select mdk. With this you can start AND stop each mode individualy.

**Comment by chrisk44** [comment]
Also, changing the absolute path option is useful only when the binary is in a location where PATH doesn't point to, otherwise it doesn't make any difference. It's possible that it was working without that option but you just didn't notice it.

**Comment by NetviperZ** [comment]
Everything seems to work fine, also noticed that its bug less than before, i would like to help the project, so if i can do something useful just let me know ^^

**Comment by chrisk44** [comment]
As I said above, the best way to help me for now is to just test it, and if you find bugs report them here to be fixed. A logcat is always useful (you need to enable the logcat messages option in settings). Also make sure to refer the project to anyone you know who might be interested... :)

**Comment by AutinDroid** [comment]
So, I was also thinking that chroot functionality would be nice. After the current builds get more and more stable, it would be great if you could do chroot commands. Chroot commands for the Nexus 5 would be much better as you have all the wifi cracking tools installed (NetHunterOS for the Nexus 5 has wlan0 chroot monitor mode working). We can execute bootkali from the hijacker app and be able to use reaver, wifite, pixiewps, etc., it would be a great add-on to the existing app.

**Comment by chrisk44** [comment]
I agree about additional functionality. But I don't think chroot would be the way to go here. The point of this app is having a GUI to use the tools. It doesn't matter where you have the tools installed (for all I care you could have a chroot environment isntalled and configure Hijacker to use the binaries from there. As long as you adjust your PATH variable everything would work perfectly. I'm always working on adding new features and fixing existing ones, but it requires time, patience and A LOT of testing, which I cannot do on my own. The more people test the app and report back, the faster I am able to move forward to adding new functionality.

Furthermore, I doubt anyone would be able to help with this at the moment, as the code is very difficult to understand because when I started this I was planning to use it on my own, not share it, and definately not share the code. So I was writing for me, no comments or documentation. I'm making changes to make it more readable and easier to add new features (essential even for me), but it will take some time until it is in a state that someone else will be able to understand how it works and add new features or fix anything.
