### ISSUE TITLE
how can I use this app with termux

### ISSUE THREAD

**Issue by azio7** [chrisk44/Hijacker#100]
aircrack-ng has already worked well on termux.
i just want a gui interface,but I can't run nethunter app(it seems too complicated to fixed it)

by the way,my phone only needs to change a number in a certain file to open the monitor mode.
so I guess I don't need nexmon or something.is that so?

**Comment by chrisk44** [comment]
If you have a way of switching your adapter to monitor mode and have root access, you should be able to run Hijacker. Hijacker is a standalone app, you don't need termux or any terminal emulator. You would need to adjust the Enable/Disable monitor mode commands in the app's settings if you want the app to enable/disable monitor mode automatically. You may also need to adjust the Preload command in the app's settings, and point it to any library you need airodump to preload when being launched.

Read the README's Troubleshooting section for further help.

**Comment by azio7** [comment]
now I know why.
I just use "airmon-ng check kill" and "airmon-ng start wlan0"
then it works
thanks a lot.
