### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by micdor** [chrisk44/Hijacker#12]
Nexus 5, Android 6.0.1

I had Hijacker installed with no issue previously and was working great. I recently uninstalled apl my apps for reasons.. all of them reinstalled just fine even the 2 others i had to install via apk file. When i try Hijacker i get the dreaded "app not installed"

I've tried pretty much all the suggestions, making sure it was actually uninstalled via the apps in the settings menu, trying to find any leftover directories/files from the last install, clearing cache, rebooting phone.. 

Is there anything else I can do BESIDES wiping ny phone and stsrting over?

**Comment by micdor** [comment]
Just wiped phone and started from scratch and still getting this error. Whats the deal??

**Comment by chrisk44** [comment]
This doesn't have anything to do with the app. Something else on your phone is screwing it up...

**Comment by micdor** [comment]
I just dont understand why it installed fine originally and wont reinstall even after wiping my phone. Here is a log if you can take a look. Seems to be an issue withthe certificate.


---- Apr 22, 2017 11:55:19 AM ----

04-22 11:55:20.946  1940  5003 D NetlinkSocketObserver: NeighborEvent{elapsedMs=4663616, 192.168.1.1, [D850E6D896CF], RTM_NEWNEIGH, NUD_PROBE}

04-22 11:55:20.970  2165  2165 I Binder_3: type=1400 audit(0.0:2150): avc: denied { ioctl } for path="socket:[79378]" dev="sockfs" ino=79378 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=1

04-22 11:55:20.970  2165  2165 I Binder_3: type=1400 audit(0.0:2151): avc: denied { ioctl } for path="socket:[79378]" dev="sockfs" ino=79378 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=1

04-22 11:55:20.986  2480  2480 I HK/LatinKeyboardBaseView: closing org.pocketworkstation.pckeyboard.LatinKeyboardView{cf3d10c V.ED..... ......ID 0,0-1080,620 #7f0e000a app:id/LatinkeyboardBaseView}

04-22 11:55:21.063  1940  5433 I ActivityManager: START u0 {act=android.intent.action.VIEW dat=file:///storage/emulated/0/Download/Hijacker-release-v1.2-beta.2.2-1.apk typ=application/vnd.android.package-archive flg=0x10000003 cmp=com.google.android.packageinstaller/com.android.packageinstaller.PackageInstallerActivity} from uid 10113 on display 0

04-22 11:55:21.119 20988 20988 W PackageParser: Unknown element under <manifest>: meta-data at /storage/emulated/0/Download/Hijacker-release-v1.2-beta.2.2-1.apk Binary XML file line #17

04-22 11:55:21.182  1940  1950 I art     : Background partial concurrent mark sweep GC freed 17720(1178KB) AllocSpace objects, 11(220KB) LOS objects, 33% free, 25MB/38MB, paused 2.464ms total 112.766ms

04-22 11:55:21.190  2564  2564 I Binder_8: type=1400 audit(0.0:2152): avc: denied { ioctl } for path="socket:[79645]" dev="sockfs" ino=79645 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=1

04-22 11:55:21.190  2564  2564 I Binder_8: type=1400 audit(0.0:2153): avc: denied { ioctl } for path="socket:[79645]" dev="sockfs" ino=79645 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=1

04-22 11:55:21.230  2404  2404 I Binder_5: type=1400 audit(0.0:2154): avc: denied { ioctl } for path="socket:[68279]" dev="sockfs" ino=68279 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=1

04-22 11:55:21.244  2480  2480 I HK/LatinKeyboardBaseView: closing org.pocketworkstation.pckeyboard.LatinKeyboardView{cf3d10c V.ED..... ......ID 0,0-1080,620 #7f0e000a app:id/LatinkeyboardBaseView}

04-22 11:55:21.230  2404  2404 I Binder_5: type=1400 audit(0.0:2155): avc: denied { ioctl } for path="socket:[68279]" dev="sockfs" ino=68279 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=1

04-22 11:55:21.262  1940  1978 I ActivityManager: Displayed com.google.android.packageinstaller/com.android.packageinstaller.PackageInstallerActivity: +167ms

04-22 11:55:23.051  1421  1994 D audio_hw_primary: out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=2

04-22 11:55:23.052  1940  2571 I ActivityManager: START u0 {dat=file:///storage/emulated/0/Download/Hijacker-release-v1.2-beta.2.2-1.apk cmp=com.google.android.packageinstaller/com.android.packageinstaller.InstallAppProgress (has extras)} from uid 10015 on display 0

04-22 11:55:23.062  1421  1994 D audio_hw_primary: select_devices: out_snd_device(2: speaker) in_snd_device(0: none)

04-22 11:55:23.062  1421  1994 D msm8974_platform: platform_send_audio_calibration: sending audio calibration for snd_device(2) acdb_id(15)

04-22 11:55:23.062  1421  1994 D audio_hw_primary: enable_snd_device: snd_device(2: speaker)

04-22 11:55:23.066  1421  1994 D audio_hw_primary: enable_audio_route: apply and update mixer path: low-latency-playback

04-22 11:55:23.100  2371  2371 I Binder_4: type=1400 audit(0.0:2156): avc: denied { ioctl } for path="socket:[79652]" dev="sockfs" ino=79652 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=1

04-22 11:55:23.100  2371  2371 I Binder_4: type=1400 audit(0.0:2157): avc: denied { ioctl } for path="socket:[79652]" dev="sockfs" ino=79652 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=1

04-22 11:55:23.124 22466 22466 I Finsky  : [1] com.google.android.vending.verifier.PackageVerificationReceiver.onReceive(1101): Skipping verification. Disabled by user setting

04-22 11:55:23.140 21002 21012 D DefContainer: Copying /storage/emulated/0/Download/Hijacker-release-v1.2-beta.2.2-1.apk to base.apk

04-22 11:55:23.175  1940  1978 I ActivityManager: Displayed com.google.android.packageinstaller/com.android.packageinstaller.InstallAppProgress: +118ms

04-22 11:55:23.160  2571  2571 I Binder_9: type=1400 audit(0.0:2158): avc: denied { ioctl } for path="socket:[68279]" dev="sockfs" ino=68279 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=1

04-22 11:55:23.160  2571  2571 I Binder_9: type=1400 audit(0.0:2159): avc: denied { ioctl } for path="socket:[68279]" dev="sockfs" ino=68279 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=1

04-22 11:55:23.182  2480  2480 I HK/LatinKeyboardBaseView: closing org.pocketworkstation.pckeyboard.LatinKeyboardView{cf3d10c V.ED..... ......ID 0,0-1080,620 #7f0e000a app:id/LatinkeyboardBaseView}

04-22 11:55:23.224 20988 21000 D OpenGLRenderer: endAllStagingAnimators on 0xb3804680 (RippleDrawable) with handle 0xacb75bd0

04-22 11:55:23.282  1940  1984 W PackageParser: Unknown element under <manifest>: meta-data at /data/app/vmdl1078171179.tmp/base.apk Binary XML file line #17

04-22 11:55:23.297  1940  1984 W PackageManager: Failed collect during installPackageLI

04-22 11:55:23.297  1940  1984 W PackageManager: android.content.pm.PackageParser$PackageParserException: Package /data/app/vmdl1078171179.tmp/base.apk has no certificates at entry AndroidManifest.xml

04-22 11:55:23.297  1940  1984 W PackageManager: 	at android.content.pm.PackageParser.collectCertificates(PackageParser.java:1105)

04-22 11:55:23.297  1940  1984 W PackageManager: 	at android.content.pm.PackageParser.collectCertificates(PackageParser.java:1058)

04-22 11:55:23.297  1940  1984 W PackageManager: 	at com.android.server.pm.PackageManagerService.installPackageLI(PackageManagerService.java:12508)

04-22 11:55:23.297  1940  1984 W PackageManager: 	at com.android.server.pm.PackageManagerService.-wrap25(PackageManagerService.java)

04-22 11:55:23.297  1940  1984 W PackageManager: 	at com.android.server.pm.PackageManagerService$9.run(PackageManagerService.java:10410)

04-22 11:55:23.297  1940  1984 W PackageManager: 	at android.os.Handler.handleCallback(Handler.java:739)

04-22 11:55:23.297  1940  1984 W PackageManager: 	at android.os.Handler.dispatchMessage(Handler.java:95)

04-22 11:55:23.297  1940  1984 W PackageManager: 	at android.os.Looper.loop(Looper.java:148)

04-22 11:55:23.297  1940  1984 W PackageManager: 	at android.os.HandlerThread.run(HandlerThread.java:61)

04-22 11:55:23.297  1940  1984 W PackageManager: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)

04-22 11:55:23.303  1940  1984 I art     : Starting a blocking GC Explicit

04-22 11:55:23.361  1940  1984 I art     : Explicit concurrent mark sweep GC freed 4756(330KB) AllocSpace objects, 0(0B) LOS objects, 33% free, 25MB/38MB, paused 1.151ms total 55.952ms

04-22 11:55:23.369 20988 20988 D InstallAppProgress: Installation error code: -103

04-22 11:55:23.411   182   182 W SurfaceFlinger: couldn't log to binary event log: overflow.

04-22 11:55:24.209  1940  2101 D ConnectivityService: notifyType CAP_CHANGED for NetworkAgentInfo [WIFI () - 101]

04-22 11:55:26.205 20988 20988 I InstallAppProgress: Finished installing com.hijacker

04-22 11:55:26.218  1421  1994 D audio_hw_primary: out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=2

04-22 11:55:26.330  2451  2451 I Binder_6: type=1400 audit(0.0:2160): avc: denied { ioctl } for path="socket:[79378]" dev="sockfs" ino=79378 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=1

04-22 11:55:26.341  2480  2480 I HK/LatinKeyboardBaseView: closing org.pocketworkstation.pckeyboard.LatinKeyboardView{cf3d10c V.ED..... ......ID 0,0-1080,620 #7f0e000a app:id/LatinkeyboardBaseView}

04-22 11:55:26.330  2451  2451 I Binder_6: type=1400 audit(0.0:2161): avc: denied { ioctl } for path="socket:[79378]" dev="sockfs" ino=79378 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=1

04-22 11:55:26.352 20988 21000 D OpenGLRenderer: endAllStagingAnimators on 0xa0cb0c00 (RippleDrawable) with handle 0xaed67b20

04-22 11:55:27.227  1940  2101 D ConnectivityService: notifyType CAP_CHANGED for NetworkAgentInfo [WIFI () - 101]

04-22 11:55:28.510  2371  2371 I Binder_4: type=1400 audit(0.0:2162): avc: denied { ioctl } for path="socket:[78411]" dev="sockfs" ino=78411 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=1

04-22 11:55:28.510  2371  2371 I Binder_4: type=1400 audit(0.0:2163): avc: denied { ioctl } for path="socket:[78411]" dev="sockfs" ino=78411 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=1

04-22 11:55:28.524  2480  2480 I HK/LatinKeyboardBaseView: closing org.pocketworkstation.pckeyboard.LatinKeyboardView{cf3d10c V.ED..... ......ID 0,0-1080,620 #7f0e000a app:id/LatinkeyboardBaseView}

---- Apr 22, 2017 11:55:29 AM ----

**Comment by chrisk44** [comment]
What Android version are you running?

**Comment by micdor** [comment]
6.0.1

**Comment by chrisk44** [comment]
This is not an app issue. The problem is with the OS.
