### ISSUE TITLE
"App not installed"  LG D821

### ISSUE THREAD

**Issue by mayday77** [chrisk44/Hijacker#13]
uname -a : Linux Kali 3.4.0 
Can't install latest 2 versions =(

**Comment by chrisk44** [comment]
Android version?

**Comment by mayday77** [comment]
6.0.1

**Comment by chrisk44** [comment]
What exactly is the last version that works?

**Comment by mayday77** [comment]
v 1.1.-beta1

**Comment by chrisk44** [comment]
There might be a problem with the build tools. Will upload here a new version for you to test in a few minutes.

**Comment by mayday77** [comment]
Thank you

**Comment by chrisk44** [comment]
Download it and tell me if it works.
https://drive.google.com/open?id=0B7Gu7Do5zhjYR3dLcF9PNFVEVEk

**Comment by mayday77** [comment]
Damn. The same ! 
Was uninstall prev version too , still no luck

**Comment by chrisk44** [comment]
Ok, fear not, I have a plan... Will upload a new one...

**Comment by chrisk44** [comment]
https://drive.google.com/open?id=0B7Gu7Do5zhjYTEtRcUxqQ3VWc1E

**Comment by mayday77** [comment]
The same

**Comment by chrisk44** [comment]
https://drive.google.com/open?id=0B7Gu7Do5zhjYX0tWYUgxT0l5clU

**Comment by mayday77** [comment]
The same, sorry ==(((((((

**Comment by chrisk44** [comment]
Ok, I'm out of ideas. Post a logcat...

**Comment by mayday77** [comment]
how can i post log ?

**Comment by chrisk44** [comment]
Run 'logcat -d' in a root shell and send me the output.

**Comment by chrisk44** [comment]
First run logcat -c to clear it, then try to install the app, then run logcat -d and send the output...

**Comment by mayday77** [comment]
Hope is it 


u0_a84@hammerhead:/ $ logcat -d
--------- beginning of main
04-27 19:12:35.611 16104 16104 D new getView: 0
04-27 19:12:35.611 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:12:35.611 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:12:35.613 16104 16104 D new getView: 0
04-27 19:12:35.613 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:12:35.613 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:12:35.670 16104 16104 D new getView: 0
04-27 19:12:35.670 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:12:35.670 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:12:35.674 16104 16104 D new getView: 0
04-27 19:12:35.674 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:12:35.674 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:12:35.678 16104 16104 D new getView: 0
04-27 19:12:35.678 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:12:35.678 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:12:48.319 16104 16104 V Term    : onCreate
04-27 19:12:48.368 16104 16104 I Term    : Bound to TermService
04-27 19:12:48.368 16104 16104 I TermService: Activity binding to service
04-27 19:12:48.373 16104 16104 D populateWindowList: in Not null
04-27 19:12:48.373 16104 16104 D onUpdate: 0
04-27 19:12:48.373 16104 16104 D onUpdate: 0
04-27 19:12:48.373 16104 16104 D populateWindowList: in mWinListAdapter = null
04-27 19:12:48.373 16104 16104 D populateWindowList: curLength  == null
04-27 19:12:48.377 16104 16104 D new getView: 0
04-27 19:12:48.377 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:12:48.377 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:12:48.377 16104 16104 D new getView: 0
04-27 19:12:48.377 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:12:48.377 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:12:48.410 16104 16104 D mWinListItemSelected: 0
04-27 19:12:48.412 16104 16104 D onUpdate: 0
04-27 19:12:48.413 16104 16104 D new getView: 0
04-27 19:12:48.413 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:12:48.413 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:12:48.417 16104 16104 D new getView: 0
04-27 19:12:48.417 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:12:48.417 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:12:48.426 16104 16104 D new getView: 0
04-27 19:12:48.426 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:12:48.426 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:12:48.470 16104 16104 D new getView: 0
04-27 19:12:48.470 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:12:48.470 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:12:48.472 16104 16104 D new getView: 0
04-27 19:12:48.472 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:12:48.472 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:12:48.479 16104 16104 D new getView: 0
04-27 19:12:48.479 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:12:48.479 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:12:49.415 16104 16104 V Term    : onCreate
04-27 19:12:49.475 16104 16104 W IInputConnectionWrapper: getExtractedText on inactive InputConnection
04-27 19:12:49.475 16104 16104 I Term    : Bound to TermService
04-27 19:12:49.475 16104 16104 I TermService: Activity binding to service
04-27 19:12:49.479 16104 16104 D populateWindowList: in Not null
04-27 19:12:49.479 16104 16104 D onUpdate: 0
04-27 19:12:49.479 16104 16104 D onUpdate: 0
04-27 19:12:49.479 16104 16104 D populateWindowList: in mWinListAdapter = null
04-27 19:12:49.480 16104 16104 D populateWindowList: curLength  == null
04-27 19:12:49.488 16104 16104 D new getView: 0
04-27 19:12:49.488 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:12:49.488 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:12:49.489 16104 16104 D new getView: 0
04-27 19:12:49.489 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:12:49.489 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:12:49.516 16104 16104 W IInputConnectionWrapper: getExtractedText on inactive InputConnection
04-27 19:12:49.525 16104 16104 D mWinListItemSelected: 0
04-27 19:12:49.527 16104 16104 D onUpdate: 0
04-27 19:12:49.528 16104 16104 D new getView: 0
04-27 19:12:49.528 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:12:49.528 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:12:49.529 16104 16104 D new getView: 0
04-27 19:12:49.529 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:12:49.529 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:12:49.530 16104 16104 D new getView: 0
04-27 19:12:49.530 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:12:49.530 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:12:49.539 16104 16104 W IInputConnectionWrapper: clearMetaKeyStates on inactive InputConnection
04-27 19:12:49.539 16104 16104 W IInputConnectionWrapper: getExtractedText on inactive InputConnection
04-27 19:12:49.573 16104 16104 D new getView: 0
04-27 19:12:49.573 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:12:49.573 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:12:49.574 16104 16104 D new getView: 0
04-27 19:12:49.574 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:12:49.574 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:12:49.577 16104 16104 D new getView: 0
04-27 19:12:49.577 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:12:49.577 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:12:49.623 16104 16104 D new getView: 0
04-27 19:12:49.623 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:12:49.623 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:12:49.625 16104 16104 D new getView: 0
04-27 19:12:49.625 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:12:49.625 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:12:55.422 16104 16104 D new getView: 0
04-27 19:12:55.422 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:12:55.422 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:12:55.423 16104 16104 D new getView: 0
04-27 19:12:55.423 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:12:55.423 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:13:01.540 16104 16104 D onupdateeeeee: tamano 0
04-27 19:13:01.562 16104 16104 D onUpdate: 0
04-27 19:13:01.562 16104 16104 D noning FINISH: ???
04-27 19:13:01.564 16104 16104 D NOSCREENS?: ?NOSCREENS??
04-27 19:13:01.565 16104 25125 I Term    : Subprocess exited: 129
04-27 19:13:01.681 16104 16104 D norunning EXIT: ???
04-27 19:13:01.732 16104 16104 W IInputConnectionWrapper: clearMetaKeyStates on inactive InputConnection
04-27 19:13:04.393 16104 16104 V Term    : onCreate
04-27 19:13:04.450 16104 16104 D Term    : TermService started
04-27 19:13:04.451 16104 16104 I TermService: Activity called onBind()
04-27 19:13:04.487 16104 16104 I Term    : Bound to TermService
04-27 19:13:04.487 16104 16104 I TermService: Activity binding to service
04-27 19:13:04.487 16104 16104 D doCreateWin: creating
04-27 19:13:04.499 16104 16104 D populateWindowList: in Not null
04-27 19:13:04.499 16104 16104 D onUpdate: 0
04-27 19:13:04.499 16104 16104 D onUpdate: 0
04-27 19:13:04.499 16104 16104 D populateWindowList: in mWinListAdapter = null
04-27 19:13:04.499 16104 16104 D populateWindowList: curLength  == null
04-27 19:13:05.043 16104 16104 E WindowManager:
04-27 19:13:05.043 16104 16104 E WindowManager: android.view.WindowLeaked: Activity com.offsec.nhterm.Term has leaked window com.android.internal.policy.PhoneWindow$DecorView{f30cc7c V.E...... R.....I. 0,0-1026,399} that was originally added here
04-27 19:13:05.043 16104 16104 E WindowManager:         at android.view.ViewRootImpl.<init>(ViewRootImpl.java:368)
04-27 19:13:05.043 16104 16104 E WindowManager:         at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:299)
04-27 19:13:05.043 16104 16104 E WindowManager:         at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
04-27 19:13:05.043 16104 16104 E WindowManager:         at android.app.Dialog.show(Dialog.java:319)
04-27 19:13:05.043 16104 16104 E WindowManager:         at com.offsec.nhterm.Term.show_shell_dialog(Term.java:881)
04-27 19:13:05.043 16104 16104 E WindowManager:         at com.offsec.nhterm.Term.populateViewFlipper(Term.java:481)
04-27 19:13:05.043 16104 16104 E WindowManager:         at com.offsec.nhterm.Term.access$400(Term.java:86)
04-27 19:13:05.043 16104 16104 E WindowManager:         at com.offsec.nhterm.Term$2.onServiceConnected(Term.java:161)
04-27 19:13:05.043 16104 16104 E WindowManager:         at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1223)
04-27 19:13:05.043 16104 16104 E WindowManager:         at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1240)
04-27 19:13:05.043 16104 16104 E WindowManager:         at android.os.Handler.handleCallback(Handler.java:739)
04-27 19:13:05.043 16104 16104 E WindowManager:         at android.os.Handler.dispatchMessage(Handler.java:95)
04-27 19:13:05.043 16104 16104 E WindowManager:         at android.os.Looper.loop(Looper.java:148)04-27 19:13:05.043 16104 16104 E WindowManager:         at android.app.ActivityThread.main(ActivityThread.java:5417)
04-27 19:13:05.043 16104 16104 E WindowManager:         at java.lang.reflect.Method.invoke(Native Method)
04-27 19:13:05.043 16104 16104 E WindowManager:         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
04-27 19:13:05.043 16104 16104 E WindowManager:         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
04-27 19:13:05.053 16104 16104 V Term    : onCreate
04-27 19:13:05.138 16104 16104 I Term    : Bound to TermService
04-27 19:13:05.138 16104 16104 I TermService: Activity binding to service
04-27 19:13:05.138 16104 16104 D doCreateWin: creating
04-27 19:13:05.157 16104 16104 D populateWindowList: in Not null
04-27 19:13:05.157 16104 16104 D onUpdate: 0
04-27 19:13:05.157 16104 16104 D onUpdate: 0
04-27 19:13:05.157 16104 16104 D populateWindowList: in mWinListAdapter = null
04-27 19:13:05.158 16104 16104 D populateWindowList: curLength  == null
04-27 19:13:06.104 16104 16104 D CANCELED: CANCELED
04-27 19:13:06.104 16104 16104 D MM createTermSession: /system/bin/sh -cmd:
04-27 19:13:06.104 16104 16104 D CS: shell: /system/bin/sh -04-27 19:13:06.104 16104 16104 D CS parse: : /system/bin/sh -
04-27 19:13:06.117 16104 16104 D STS: ^^ : /system/bin/sh - cmd:
04-27 19:13:06.117 16104 16104 D onUpdate: 0
04-27 19:13:06.131 16104 16104 D new getView: 0
04-27 19:13:06.131 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:13:06.131 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:13:06.133 16104 16104 D new getView: 0
04-27 19:13:06.133 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:13:06.133 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:13:06.137 16104 16104 D new getView: 0
04-27 19:13:06.137 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:13:06.137 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:13:06.148 16104 25621 I Term    : waiting for: 25618
04-27 19:13:06.160 16104 16104 D mWinListItemSelected: 0
04-27 19:13:06.162 16104 16104 D onUpdate: 0
04-27 19:13:06.163 16104 16104 D new getView: 0
04-27 19:13:06.163 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:13:06.163 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:13:06.164 16104 16104 D new getView: 0
04-27 19:13:06.164 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:13:06.164 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:13:06.165 16104 16104 D new getView: 0
04-27 19:13:06.165 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:13:06.165 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:13:07.128 16104 16104 D new getView: 0
04-27 19:13:07.128 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:13:07.128 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:13:07.129 16104 16104 D new getView: 0
04-27 19:13:07.129 16104 16104 D mPendingPathBroadcasts: Tamano = 1
04-27 19:13:07.129 16104 16104 D mPendingPathBroadcasts: Tamano = 1
u0_a84@hammerhead:/ $

**Comment by chrisk44** [comment]
This doesn't give me anything. If you have the apk file version 1.2-beta.1 try to install it again to make sure it works.

**Comment by mayday77** [comment]
sory Chris , can't locate a v 1.1.-beta1.apk file 
Why did i uninstall this! =(((

**Comment by chrisk44** [comment]
https://drive.google.com/open?id=0B7Gu7Do5zhjYU0pFZ2JhYzFUbDA
Try this...

**Comment by mayday77** [comment]
The Same 
Can you please bring back 1.1.-beta1.apk  ?

**Comment by chrisk44** [comment]
https://drive.google.com/open?id=0B7Gu7Do5zhjYTTk2eFNZZzJNMGc

**Comment by mayday77** [comment]
no ...

**Comment by chrisk44** [comment]
that's v1.2-beta.1, the problem is your device...

**Comment by mayday77** [comment]
1.1.-beta1.apk working well before i delete it

**Comment by chrisk44** [comment]
1.1? I thought that 1.2-beta.1 was working...
https://drive.google.com/open?id=0B7Gu7Do5zhjYdl83N3dvSVh4Q0U

**Comment by chrisk44** [comment]
Did it work?

**Comment by mayday77** [comment]
Nope,i've lost my hope :/

**Comment by chrisk44** [comment]
I think I got it, try v1.3-exp.1.3.

**Comment by mayday77** [comment]
Yes
Yes
Yes
Yes!!!!!! Thank you !!!!!!!!
Issue was ...?hmm?

**Comment by chrisk44** [comment]
Appearently, since android version 7+ there are 2 types of certificates to sign the apk. When Android Studio was updated to support both of them, I unknowingly checked only V2 leaving V1 unchecked. Without the certificate for up to Android 6, your installer denied installing it because it seemed unsigned. I didn't notice it because I test on Nougat.

The Android Studio update was the only change that has happened to the build process apart for the build tools and I completely forgot about it.

By the way, thanks to @bingobongo1008 for mentioning it [here](https://github.com/chrisk44/Hijacker/issues/14).
