### ISSUE TITLE
INSTALL_PARSE_FAILED_NO_CERTIFICATES

### ISSUE THREAD

**Issue by bingobongo1008** [chrisk44/Hijacker#14]
I get the following when attempting to install v 1.1,2,3 using the Nexus Root Toolkit apk install facility:

Nexus Root Toolkit v2.1.9

Masterlists:
- LatestToolkitFiles.ini	3150
- AndroidDeviceListFull.ini	3150
- AndroidDeviceListFlash.ini	3150

HAMMERHEAD-HAMMERHEAD: Android 6.0.1 - Build: M4B30Z

Live log initiated [2017-04-28]:

Installing Hijacker-release-v1.3-exp.1.apk to your device:
adb install "C:\Users\Helios\Downloads\Hijacker-release-v1.3-exp.1.apk"
[  1%] /data/local/tmp/Hijacker-release-v1.3-exp.1.apk
[  2%] /data/local/tmp/Hijacker-release-v1.3-exp.1.apk
..
[100%] /data/local/tmp/Hijacker-release-v1.3-exp.1.apk
	pkg: /data/local/tmp/Hijacker-release-v1.3-exp.1.apk

Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES]
=====================================
How do I get past the certificate issue? (nethunter/android newbie here..)

**Comment by chrisk44** [comment]
I have no idea what this is. Can't you just install it with the default android APK Installer?

**Comment by chrisk44** [comment]
Oh sorry, I uploaded the non-signed apk. :P My bad, uploading the correct one...

**Comment by bingobongo1008** [comment]
Same issue with v1.3-exp1.2.apk

  99%] /data/local/tmp/Hijacker-release-v1.3-exp.1.2.apk
[100%] /data/local/tmp/Hijacker-release-v1.3-exp.1.2.apk
	pkg: /data/local/tmp/Hijacker-release-v1.3-exp.1.2.apk

Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES]

**Comment by chrisk44** [comment]
Well, I don't know what's happening. The app is, and always has been, signed with a certificate.

**Comment by bingobongo1008** [comment]
Sorry to insist, but are you sure? 
When I open the .apk in winrar, there is no .RSA or certificate file in the META-INF folder where can I find the signature file otherwise? Note there are 2 versions of signatures, for android 7+ and android 6-. 
Signed .apks should include both v1 and v2 signatures.

**Comment by chrisk44** [comment]
Ohhhhhhhhh that explains a lot. It's that new option of Android Studio. OK, I will fix it as soon as I get home and upload it.

**Comment by bingobongo1008** [comment]
Yay, success!! :)
