### ISSUE TITLE
detecting nethunter/kali

### ISSUE THREAD

**Issue by bingobongo1008** [chrisk44/Hijacker#15]
I'm using nethunter on a nexus 5.
However testing tools fails on Kali chroot, says it doesn't find bootkali_ini
and the reaver attack has pixie dust disabled since requires Nethunter chroot.

I'm definitely on nethunter. My nethunter kali chroot manager checks for chroot at /data/local/nhsystem/kali-armhf

What can I do to enable some pixie-dust?

**Comment by chrisk44** [comment]
Can you please give me the outputs of:

`echo $PATH` and
`which bootkali_init` or `whereis bootkali_init`

**Comment by mayday77** [comment]
root@kali:~# echo $PATCH

root@kali:~# which bootkali_init
root@kali:~#

**Comment by mayday77** [comment]
The same problem and since first version

**Comment by chrisk44** [comment]
the command is `echo $PATH`, not `echo $PATCH` and is really not useful unless I also know where the actual bootkali_init file is.

**Comment by mayday77** [comment]
Lol  my fault. Sorry

root@kali:~# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/system/xbin
root@kali:~#


root@kali:~# whereis bootkali_init
bootkali_init:
root@kali:~#

**Comment by chrisk44** [comment]
Is it in /data/data/com.offsec.nethunter/files/scripts or something like that?

**Comment by bingobongo1008** [comment]
Hello Chris, I have the same path as Mayday.
There is a /system/bin/bootkali link that points to the
/data/com.offsec.../bookali script you mentioned, however it is
inaccessible from the kali terminal (there is no /data)

However, using the androidsu terminal, /data is accessible and so is the
/data/data/com.offsec.nethunter/files/scripts/bootkali script.
Nonetheless, even in androidsu terminal, which/whereis bootkali_init return
nothing, and it is not in the scripts folder.

**Comment by chrisk44** [comment]
So there isn't a bootkali_init in that 'scripts' folder? Test the latest version, I have made some changes.

**Comment by mayday77** [comment]
6 taps on version is hidden feature ?;)

**Comment by chrisk44** [comment]
Completely irrelevant to this issue... It's a dev menu; connect to server, crash the app etc... Are you the one who sent a bug report for that crash?

**Comment by mayday77** [comment]
Nope , sir.
Can't find a donate button

**Comment by chrisk44** [comment]
There is a donate button on the project's homepage...

**Comment by bingobongo1008** [comment]
Chris: correct, no bootkali_init in the com.offsec.nethunter/files/scripts
folder for androidsu.
I tested w 1.3 pk 3, same issues.

**Comment by chrisk44** [comment]
What about bootkali_bash?

**Comment by bingobongo1008** [comment]
Yes, bootkali_bash, and bootkali_login are present. I tried bootkali_bash
and it puts me into root@kali, but still no _init file created.

**Comment by chrisk44** [comment]
Ok, so I suppose that since you are in nethunter, the kali chroot environment is already initialized, I'll make the app use bootkali_bash for nethunter. Will upload a test release here in a few minutes.

**Comment by chrisk44** [comment]
https://drive.google.com/open?id=0B7Gu7Do5zhjYWmhVWHJiYmdGdkk

**Comment by mayday77** [comment]
:all test passed ,chroot found.
I was run kali nethunter app,and ooen chroot manager ,here is a path to the chroot directory. Added this path to the app and all test passed.
Thank you again !!!!!

**Comment by chrisk44** [comment]
Glad I helped.

**Comment by bingobongo1008** [comment]
Mayday which folder did you select, nethunter or a subdir?

**Comment by chrisk44** [comment]
You select the folder that contains the filesystem... /bin, /boot, /dev, /etc...

**Comment by bingobongo1008** [comment]
Nevermind, selecting nhsystem/kali-armhf and then running the test suite
works correctly!

**Comment by mayday77** [comment]
![screenshot_20170501-171807](https://cloud.githubusercontent.com/assets/6366522/25581741/4598b234-2e92-11e7-82f9-0158f473a165.png)
![screenshot_20170501-171745](https://cloud.githubusercontent.com/assets/6366522/25581744/4a341d74-2e92-11e7-9ba4-9e6388eac09f.png)

**Comment by bingobongo1008** [comment]
Thank you!!

**Comment by ssofiian** [comment]
Hello crisck

**Comment by ssofiian** [comment]
I have nexus 5 with both monitor mode (internal.external) . Installed kali-nethuter-OS my problem its . How run reaver with pixie-dust used apk hijacker inside chroot.can you explain to me step by step pleaze . Thnk you

**Comment by ssofiian** [comment]
And if i download zip file from github.com how excute in nethunter ?
