### ISSUE TITLE
Can't use WiFi in managed mode 

### ISSUE THREAD

**Issue by 0v3rfl00w** [chrisk44/Hijacker#18]
Monitoring mode works fine . but can't use WiFi to connect even after monitor mode is turned off and the phone is  rebooted : authentication error

**Comment by 0v3rfl00w** [comment]
I am running android 7.1.2 on sprint lg g3

**Comment by chrisk44** [comment]
Are you using the internal wireless adapter or an external one?

**Comment by 0v3rfl00w** [comment]
internal wireless adapter and even the injection is working

**Comment by chrisk44** [comment]
Well, if the problem persists even after a reboot it probably has something to do with the nexmon firmware and not the app itself. That is, IF you use the firmware included in the app.
Make sure that your device's hardware is compatible with it and then I suggest you reach out to the official [nexmon](https://github.com/seemoo-lab/nexmon) repo for help about this.

**Comment by 0v3rfl00w** [comment]
yes this have to do  probably with the nexmon firmware and android 7
