### ISSUE TITLE
How to configure Hijacker to work with an external adapter

### ISSUE THREAD

**Issue by v00x** [chrisk44/Hijacker#19]
My device's wifi chip doesn't monitor mode or injecting packets so i bought tp-link wn722n. I have custom CM 5.1.1 rom the kernel recognizes the adapter and when i type lsusb in the chrooted linux system or emulator it shows the anthena. 
But i don't know gow to point the app to use the signal from this adapter.
In the readme i see that when i use external adapter is not necessary to install nexmon firmware, so if i use chrooted system i only need to install the firmware drivers for my adapter?

**Comment by chrisk44** [comment]
First of all, the kali chroot environment and Hijacker are 2 completely different and independent things. Hijacker can only USE an existing chroot environment for one specific attack.

What you are trying to do (I suspect, given that you commented on Hijacker) is to use Hijacker with an external adapter. For this, you need an adapter that supports monitor mode AND that has a firmware to support monitor mode IN ANDROID. (The nexmon firmware is only for BCM4339, you need a custom firmware for each adapter you want to use)

After you make sure the adapter is connected to your device and you have installed a firmware for it to support monitor mode, all you need to do is run iwconfig to get the name of the external interface and then go to the app's settings and use the first option "Interface" to tell the app what to use. You can also set the "enable/disable monitor mode" commands so the app can enable/disable the monitor mode for the interface so you won't have to do it manually every time you want to use the app.

If you don't understand any of this, you probably shouldn't use this app.
