### ISSUE TITLE
Build .14 crashes when cracking or DoS is pressed

### ISSUE THREAD

**Issue by AutinDroid** [chrisk44/Hijacker#2]
I saw the new  app build today, download, and ran it, but it crashes when I want to DoS or crack a network. Logcat: 12-01 07:06:38.343 E/AndroidRuntime(18763): Process: com.hijacker, PID: 18763. 12-01 07:06:38.343 E/AndroidRuntime(18763): 	at com.hijacker.MainActivity.startMdk(MainActivity.java:497)
12-01 07:06:38.343 E/AndroidRuntime(18763): 	at com.hijacker.MyListFragment$1.onMenuItemClick(MyListFragment.java:108)

**Comment by chrisk44** [comment]
It doesn't crash on my device. Remove the app completely and install it again. If the problem persists, post a full logcat, this part does not make any sense to me. Also, make sure that "Logcat Messages" is enabled in settings.

**Comment by chrisk44** [comment]
I don't know why this would cause a problem, but I've already changed the code that caused the crash. I'll upload a 0.14.2 version in a few minutes.

**Comment by NetviperZ** [comment]
I can confirm that its doesn't crash on my device neither, everything works very well

**Comment by AutinDroid** [comment]
Built 0.15 fixed the crack issue, but DoS still crashes. I have sent a bug report via email.

**Comment by NetviperZ** [comment]
@AutinDroid did MDK3 pass on test tools ?

**Comment by AutinDroid** [comment]
Just tested, and it didn't.

**Comment by NetviperZ** [comment]
I had the same issue, after adding /su/xbin/mdk3 on "MDK3 absolute path" on the setting the problem seems be fixed!

**Comment by AutinDroid** [comment]
Great find! That seemed to have fixed the problem!

**Comment by chrisk44** [comment]
if mdk3 fails the test, it's most likely because you have the faulty version of the nexmon app. If that's the case, you need to install the tools with Hijacker in the same directory you installed them with nexmon, or install them somewhere else and adjust the absolute path, as suggested.

**Comment by NetviperZ** [comment]
I am glad to have been of some help ^^
