### ISSUE TITLE
crash on LG G3

### ISSUE THREAD

**Issue by cn0xroot** [chrisk44/Hijacker#21]
can't run it on G3

```
Device:LG D857
Android version：6.0
Soft version:D858HK30a-HKG-XX
```

**Comment by chrisk44** [comment]
What do you mean "can't run it"? Doesn't install, doesn't run?

**Comment by cn0xroot** [comment]
doesn't run it's stop.

**Comment by chrisk44** [comment]
Does the bug report activity start? Did you send a bug report?

**Comment by cn0xroot** [comment]
no,it just show "Unfortunately Hijacker has stopped"

**Comment by chrisk44** [comment]
Can you post a logcat? Clear it, open the app, and post the new logcat here.

**Comment by chrisk44** [comment]
I also uploaded a new apk (v1.3-stable.3), try it.

**Comment by cn0xroot** [comment]
v1.3-stable.3 has the same result。i'll try to get logcat info

**Comment by chrisk44** [comment]
Is there any progress with this, or should I close it?
