### ISSUE TITLE
Doesn't detect my external wifi card

### ISSUE THREAD

**Issue by FFY00** [chrisk44/Hijacker#22]
I tested with a TL-WN722N (ar9271). The drivers are obviously enabled and with Nethunter chroot I can successfully enable monitor mode and run aircrack.

**Comment by chrisk44** [comment]
You need to set the interface name in the app's settings. The default is wlan0, which is the internal wireless adapter, so you have to set it to whatever name the external adapter has.

**Comment by FFY00** [comment]
Ok, It's working now, however I need to manually enable the monitor mode in th kali chroot. I tried to change the airmon command to be executed inside the kali chroot but without any luck.

**Comment by chrisk44** [comment]
There should be a way to enable monitor mode in android. Then, you can use the "Enable/Disable monitor mode" settings of Hijacker so the app does it automatically for you.

**Comment by EvilAirborn** [comment]
add airmon-ng bash to the assets section to fix the problem

**Comment by FFY00** [comment]
where?

**Comment by EvilAirborn** [comment]
Sorry I meant in github repo,let me check first,if work I will submit a pull request and submit a release

**Comment by FFY00** [comment]
Ok, thanks.

**Comment by chrisk44** [comment]
Solved?

**Comment by FFY00** [comment]
Yes, I can close now.
