### ISSUE TITLE
Pixie-Dust Linking To Hijacker Without Chroot

### ISSUE THREAD

**Issue by EvilAirborn** [chrisk44/Hijacker#26]
![screenshot_20171005-170317_20171005175047120](https://user-images.githubusercontent.com/28428050/31225863-c77960e4-a9f5-11e7-81ab-22a0719aea90.jpg)

If you see in the pic,I some how tried to link the pixiewps to hijacker without chroot environment.This Thing Run Inside Hijacker Not In Chroot Mode......I compiled reaver t6x forked for Android and pixiewps 1.2.2 for android.....and put in the assets folder of hijacker. Then changed the Smalldh symbol from -S to -K using android studio,so if I check smalldh key,it add -K instead of -S in reaver...I am too lazy so I did this.......after this I ran reaver t6x fork android without chroot using external WiFi adeptor....but it don't executes the pixiewps command.I put the hijacker commands in androidsu,same things happens..but when I ran the pixiewps commands that comes from the reaver! It works and give me pin! In Android su......So is there anyway to force terminal to execute that command automatically! Then you can make hijacker app independent!!!!!!!

**Comment by chrisk44** [comment]
Alright, now this interesting. So you have a reaver binary that includes the pixie-dust attack and works in android by itself? Upload it here...

**Comment by EvilAirborn** [comment]
OK wait

**Comment by EvilAirborn** [comment]
[reaver.zip](https://github.com/chrisk44/Hijacker/files/1359234/reaver.zip)
Here is it!

**Comment by EvilAirborn** [comment]
Make Sure to use external WiFi.coz source monstart-nh won't work with it in androidsu

**Comment by EvilAirborn** [comment]
How is you progress going on? Working?

**Comment by chrisk44** [comment]
Your binary doesn't seem to work. It gets stuck at "Waiting for beacon..."

**Comment by EvilAirborn** [comment]
Which Script your using to enable monitor mode? Airmon?

**Comment by chrisk44** [comment]
nexmon -m true. I have monitor mode and injection working, the binary doesn't seem to work.

**Comment by EvilAirborn** [comment]
I said nexmon will won't work with this binary.. use airmon-ng to enable
monitor mode to your external wifi adapter and then use this binary....if
it works correctly with airmon & external wifi, I will try to fix nexmon
issue,or if not work,just throw it into the dust! I will be waiting for
reply.ok?

**Comment by chrisk44** [comment]
The point here is to work with the internal adapter, and it should work if the binary is built correctly. I don't even have an external adapter, because I don't need one.

**Comment by EvilAirborn** [comment]
But it working with external wifi in AndroidSu :/

**Comment by chrisk44** [comment]
Well it doesn't work with the internal. I have tried this repo before and I was stuck here as well. There is an other issue opened here about this, someone else started working on it and then stopped. If you can make it work with the internal adapter I will be more than happy to include it in the app.

**Comment by EvilAirborn** [comment]
Hey do you know a command that execute an another command from a binary, problem is in c code insite the pixie.c ... This have everything that execute automated pixiewps command in Kali Linux or in Kali nethunter.but androidsu take it as echo!! Why?
This pixie.c includes this codes,I tried to modify but won't work.......>>>>>
#include "pixie.h"
#include "globule.h"
#include <stdio.h>
#include <stdlib.h>

struct pixie pixie = {0};

void pixie_format(const unsigned char *in, unsigned len, char *outbuf) {
	unsigned i;
	char *out = outbuf;
	for(i = 0; i < len; i++, out+=3) {
		sprintf(out, "%02x:", in[i]);
	}
	if(i) *(--out) = 0;
}

void pixie_attack(void) {
	struct pixie *p = &pixie;
	int dh_small = get_dh_small();

	if(p->do_pixie) {
		char cmd[4096];
		snprintf(cmd, sizeof cmd,"pixiewps -e %s -s %s -z %s -a %s -n %s %s %s",
		p->pke, p->ehash1, p->ehash2, p->authkey, p->enonce,
		dh_small ? "-S" : "-r" , dh_small ? "" : p->pkr);
		printf("%s\n", cmd);
		system(cmd);
		exit(0);
	}
	PIXIE_FREE(authkey);
	PIXIE_FREE(pkr);
	PIXIE_FREE(pke);
	PIXIE_FREE(enonce);
	PIXIE_FREE(ehash1);
	PIXIE_FREE(ehash2);
}

**Comment by chrisk44** [comment]
I don't think that the problem is there. It's something about reaver, it doesn't capture anything, it doesn't reach the pixie attack...

**Comment by EvilAirborn** [comment]
No it works with external. Problem is this binary ignores hooking, so then
nexutil/monstart try to hook monitor mode to the binary ,the binary
ignores.that's why it dont work with monstart!

**Comment by chrisk44** [comment]
About the previous message: The pixie-dust command is printed with `printf("%s\n", cmd);` and then ran by `system(cmd)`.

And I don't know what that last one means. I'm not including this unless I can use it with the internal adapter.

**Comment by EvilAirborn** [comment]
No The Pixiewps command didn't recognized by androidsu but Kali detect it
and executes the pixiewps..but android su take it just as printf(echo) and
the system(cmd) won't recozined by androidsu

**Comment by chrisk44** [comment]
Is pixiewps in the same folder as reaver and executable?

**Comment by NetviperZ** [comment]
Any progress guys?

**Comment by EvilAirborn** [comment]
Is pixiewps in the same folder as reaver and executable?
--
yes it was!
anyway i am back again to this project i will try to compile working one for android

**Comment by chrisk44** [comment]
Great.

**Comment by EvilAirborn** [comment]
but wht it is not exicuting pixiewps command in shell?
i am confiused about that

**Comment by EvilAirborn** [comment]
if(p->do_pixie) {
	char cmd[4096];
	snprintf(cmd, sizeof cmd,"pixiewps -e %s -s %s -z %s -a %s -n %s %s %s",
	p->pke, p->ehash1, p->ehash2, p->authkey, p->enonce,
	dh_small ? "-S" : "-r" , dh_small ? "" : p->pkr);
	printf("%s\n", cmd);
	system(cmd);
	exit(0);

**Comment by EvilAirborn** [comment]
this think should exicute the command

**Comment by EvilAirborn** [comment]
build with this statement? LDFLAGS=-static ./configure
this makes the excutable run in android

**Comment by chrisk44** [comment]
That code should work, but I haven't worked on it so I don't know what could go wrong.

About the -static flag, yes this should do the trick, but it doesn't. I tried that when I first added Reaver, but I couldn't get it to work, some linking problem at runtime I think, don't remember exactly (yes this doesn't make sense, I know).

**Comment by EvilAirborn** [comment]
hey i successfully run reaver with that -static flag!

**Comment by EvilAirborn** [comment]
successfully run in hijacker and android terminal

**Comment by EvilAirborn** [comment]
i used CFLAGS=-static insteed of LDFLAGS=-static

**Comment by chrisk44** [comment]
Really? I am so dissapointed with myself right now. Please upload the binary...

**Comment by EvilAirborn** [comment]
![screenshot_20171209-180639](https://user-images.githubusercontent.com/28428050/33795459-e0195fac-dd0b-11e7-8786-75e0b3d96f46.png)
Here is the binary
[reaver.zip](https://github.com/chrisk44/Hijacker/files/1544641/reaver.zip)

**Comment by EvilAirborn** [comment]
let me know the update what about this binary, it will wont work with nexutil because after declaring CFLAGS=-static/CFLAGS=CFLAGS-static , the reaver bash will wont accept hooking any other library...so when nexutil tries to hook libfakeioctlkali.so or libfakeioctl.so, reaver rejects to let it hook! that is the main problem i think

**Comment by chrisk44** [comment]
Seems to work for me. I will test it later...

**Comment by EvilAirborn** [comment]
okay let me get a update before you commit :)

**Comment by chrisk44** [comment]
I will.

I'm thinking about rebuilding a big part of the app to make the code better (Android best practices and whatnot) so if this works I will include it and release a "Hijacker 2.0". Or might add it now and just rebuild later... I'll see how it goes...

**Comment by chrisk44** [comment]
You are right, it doesn't work, no monitor mode. Can you statically link the libfakeioctl.so?

Or maybe just build reaver normally (dynamically linked) and maybe have the libs on the device?

**Comment by EvilAirborn** [comment]
Let me See.... Understanding Another People's Code is Literally Hard For Me,anyway let me see if I can let it hook those librarys too

**Comment by EvilAirborn** [comment]
If I build one for Android arm normally without static flag...Will it work with ldpreload,I am not sure..I have to check..but do you know anything about this?

**Comment by chrisk44** [comment]
I think it would, but then it looks for some other libs that the device doesn't have.

How did you cross compile it?

**Comment by chrisk44** [comment]
If you can build static versions of libc.so.6, libm.so.6, libpcap.so.0.8 and libfakeioctl.so and link them all to the binary, that might work. I found out what libraries it's looking for and added them in the directories it's looking for them, the binary runs with LD_PRELOAD but then it says "Can't get pcap handle" and exits. Even if it worked, I can't create these directories on the device of anyone who uses the app.

**Comment by EvilAirborn** [comment]
Dude Cross Compile Is Very Easy With CFLAGS=-static......I compiled it via nethunter os, so it automatically because compatible with armv7 ,... generally Linux on computer runs on x64 or x86 based processor, so directly compiling via Linux may not work for phone....but if you directly compile it with Kali nethunter with static flag, it will automatically run on Android shell😜,

**Comment by chrisk44** [comment]
Yeah, that's what I did, and there is a way to cross compile on PC. Anyway, I still can't run it...

**Comment by EvilAirborn** [comment]
But, library build for Linux may not work on Android Shell, so we have to compile librarys for Android, then link to that binary.but I am Confiused how I can link that librarys,

**Comment by EvilAirborn** [comment]
My binary didn't run on your Nexus 5?

**Comment by chrisk44** [comment]
Your binary runs but can't link libfakeioctl.so because it's static, so no monitor mode. Either find a way to have it dynamically built and have it lookup the libraries on runtime and then I'll include them in the app package, OR build it statically and include libfakeioctl.so. You can take it from Hijacker's directory.

**Comment by EvilAirborn** [comment]
If Their is anyway to hook libfakeioctl.so to wlan0, I mean directly enable monitor mode on wlan0 via that library?

**Comment by EvilAirborn** [comment]
I have the Android libfakeioctl.so library, but thinking if there anyway to directly make the full wlan0 put into monitor mode like the airmon-ng did

**Comment by chrisk44** [comment]
Don't know, don't think so.

**Comment by EvilAirborn** [comment]
Can I know which librarys are used by reaver fork...?

**Comment by chrisk44** [comment]
I think you mean the ones I mentioned earlier, plus the loader (ld-linux-armeabihf.so.3 I think).

**Comment by EvilAirborn** [comment]
libc.so.6, libm.so.6, libpcap.so.0.8  ,ld-linux-armeabihf.so.3  && libfakeiotcl.so........this librarys only right?

**Comment by chrisk44** [comment]
yeah

**Comment by EvilAirborn** [comment]
I need a libpcap.so.1 , I can't build that one...can you upload a one if you have that works on nexus5 arm

**Comment by chrisk44** [comment]
I have a libpcap.so.0.8 but it's not static.

**Comment by EvilAirborn** [comment]
Give it to me....

**Comment by EvilAirborn** [comment]
I have made a bully-pixie forked compiled for Android, and somehow with he editor I made it possible recozined by Android, now it's asking one by one for librarys ,

**Comment by chrisk44** [comment]
It's from the chroot environment. Run `find / -name libpcap.so.0.8 -print` to find it.

**Comment by EvilAirborn** [comment]
Chroot's librarys maybe not supposed to work on Android shell

**Comment by chrisk44** [comment]
You can build it yourself, if you want to. Also, you may want to take a look [here](https://github.com/seemoo-lab/nexmon), utilities folder. Most of the binaries I use and the libfakeioctl are from there.

**Comment by EvilAirborn** [comment]
i directly declared the library libfakeioctl.so to run in reaver static version before it run by modifying, but i gives error ''Can't get pcap handle''....this error show up in chroot environment but not in android su, while running in android su, the wifi suddendly got disconnected,and then connects back again...it means it tried to enable monitor mode,but cant..it means the android shell also cant handle pcap

**Comment by chrisk44** [comment]
I get this error in Android.

**Comment by EvilAirborn** [comment]
another problem rises,dhat......... how did you compiled and maneged to run reaver in android shell before getting that error??

**Comment by chrisk44** [comment]
I compiled it in nethunter, copied the 3 libs and the loader in Android, placed the loader in /lib and used LD_LIBRARY_PATH for the 3 libs in a custom directory. But that thing with pcap handle happens, and I have no idea why...

**Comment by EvilAirborn** [comment]
compiled with static flag? or just normally?

**Comment by chrisk44** [comment]
Both. Static doesn't need the libraries tricks and works with LD_PRELOAD, but the same error pops up.

**Comment by EvilAirborn** [comment]
can you upload that binary and 3 libs? let me check

**Comment by chrisk44** [comment]
[reaver.zip](https://github.com/chrisk44/Hijacker/files/1547702/reaver.zip)

**Comment by EvilAirborn** [comment]
you used ''export LD_LIBRARY_PATH'' in terminal command? right? or editded source code to specify the library path?

**Comment by chrisk44** [comment]
No you can just do `LD_LIBRARY_PATH="/path/to/libs" ./reaver args` like you do with LD_PRELOAD.

**Comment by EvilAirborn** [comment]
no i still getting no such a file or directory, my command" LD_LIBRARY_PATH="/system/libs" ./reaver..........this is the non static reaver , not the static one

**Comment by chrisk44** [comment]
if it doesn't specify what is missing then it can't find the loader (ld-linux-armeabihf.so). It doesn't look for this in the LD_LIBRARY_PATH, for some reason it's hardcoded to /lib/ld-linux-armeabihf.so so you need to put it there.

**Comment by chrisk44** [comment]
But it still doesn't work, so just try to fix the static one, fix the problem with pcap.

**Comment by EvilAirborn** [comment]
i putted the all library you provided in /system/lib

**Comment by EvilAirborn** [comment]
ld-linux-armeabihf.so or ld-linux-armeabihf.so.3??

**Comment by chrisk44** [comment]
ld-linux-armeabihf.so.3

**Comment by EvilAirborn** [comment]
ld-linux-armeabihf.so.3,,,this is working as loader right?

**Comment by chrisk44** [comment]
yes

**Comment by EvilAirborn** [comment]
my wifi isnt working anymore after putting you libs,just bricked my phones wifi fuctionality

**Comment by chrisk44** [comment]
I have no idea what you are talking about, mine works fine.

**Comment by EvilAirborn** [comment]
ow sorry,,,not not....my wifi was just crashed

**Comment by EvilAirborn** [comment]
tell me detail where you putted you libs and runned not static reaver......i want to know why mine not works

**Comment by chrisk44** [comment]
It's what I already said earlier.

**Comment by EvilAirborn** [comment]
I able to run reaver after creating a new directory in the root of android named lib and put the loader there,.so non static reaver works.......but my WiFi crashed again because hijacker was running in background and I commanded in terminal "source monstart-nh",,so I restarted my phone.....after restarting suddenly got problem "libdl.so.2 From LD Preload cant be Preloaded-not such a file or directory" after executing source monstart-nh in android shell :/

**Comment by EvilAirborn** [comment]
Have any idea about this problem? If you help about solving this problem,I may solve the pcap issue

**Comment by chrisk44** [comment]
Why are you messing with monstart? Aren't you using nexmon in Android?

**Comment by EvilAirborn** [comment]
Obviously, I am using nethunter is in nexus 5, I faced first time in this problem...in the /system/lib directory , I found libdl.so but not libdl.so.2

**Comment by chrisk44** [comment]
Use nethunter only to compile, don't try to run reaver in kali, there's no point. The point is to make it work on Android with the internal adapter, i.e. nexmon.

**Comment by EvilAirborn** [comment]
Find libdl.so.2 in your Android lib folder and upload...that library is missing in my Android library folder

**Comment by chrisk44** [comment]
What libdl, there is no libdl. There is `ld-linux-armeabihf.so.3`, which is a **loader**, not a library. It finds the libraries that the binary needs **when the binary is being loaded in memory**. If you build a static binary you don't need a loader.

We are most likely going to go with a static build. The one I uploaded works on android without any custom libraries, loader or anything. It just needs to LD_PRELOAD libfakeioctl.so for monitor mode and frame injection, like all the other binaries I use, because of nexmon.

Since we get a `pcap` related error, maybe something is going wrong when we build the binary in one system (kali) and then run it on another (android). You may run these on the same device, but they are quite different configurations. For example, in kali, some libraries can be found in /lib while on Android this directory doesn't even exist. So if any directory is hardcoded in the binary then it won't run on Android, so we use a static binary.

**Comment by EvilAirborn** [comment]
Dude chears, I didn't saw you last comment, just forgot it.....I successfully runed reaver fork via Android shell and hijacker too!! Yeahhhh. Just compiled a libdl.so.2...put in the ./lib/ not in the system/lib......then it started working... hijacker also able to launch it..cheers

**Comment by EvilAirborn** [comment]
The directory hardcoded to very first folder of Android system....There is no lib folder....you have to create a one....then put libdl.so.2 and your librarys

**Comment by chrisk44** [comment]
What do you mean it worked? How?

**Comment by EvilAirborn** [comment]
It's night 1am here...I will test tomorrow again to find bugs and any other problem,then we can go with hijacker 2...open a private repo and let me contribute there..once we complete build hijacker 2..we may publicly release out souce codes with realeses,.

**Comment by EvilAirborn** [comment]
It worked

**Comment by EvilAirborn** [comment]
There is a problem with your wifi,after restarting,pcap problem solved

**Comment by EvilAirborn** [comment]
And I also added libdl.so.2

**Comment by EvilAirborn** [comment]
It worked how? You made the food and I added some salt....I tested much time in this problem,at last this problem solved, tomorrow I will compile hijacker with -K agurnment...let's see if pixiewps Exicuted...it will Exicute I hope because the reaver-wps-fork-t6x successfully worked on Android shell and in hijacker shell too

**Comment by EvilAirborn** [comment]
So let me know, what should we do next?

**Comment by chrisk44** [comment]
First, you give me the binary and any libs I need to have in the Hijacker directory (and only there, nowhere else) and if it works I start working on the app itself.

**Comment by EvilAirborn** [comment]
Open A Private Repo...I share Every Details There? Not in public.okay?

**Comment by chrisk44** [comment]
Just email me.

**Comment by EvilAirborn** [comment]
Inboxed...Go to the inbox or check spam...

**Comment by ssofiian** [comment]
Hello how complite reaver with pixie-dust to run inside hijacker apk

**Comment by ssofiian** [comment]
And witch folder ?
