### ISSUE TITLE
wps info

### ISSUE THREAD

**Issue by einsteinov** [chrisk44/Hijacker#28]

**Comment by chrisk44** [comment]
A description would be appreciated...

**Comment by einsteinov** [comment]
please add wps info .To know which aps are wps enabled.

**Comment by chrisk44** [comment]
This has already been suggested. I would need to make airodump print this information, which would mess up its entire output. There is probably a way but I would need to write an important piece of the code all over again. Maybe at some point in the future. For now, there are other apps that can help you with this.
