### ISSUE TITLE
arm8l

### ISSUE THREAD

**Issue by omemishra** [chrisk44/Hijacker#29]
samsung j7 i have and its not working there

**Comment by chrisk44** [comment]
As the project's README states: the included binaries are compiled for armv7l, not armv8l. I actually think it should work, but I can't be sure. Go to Settings and try running the sample commands in a terminal. If they work, then the problem lies somewhere else, not in the CPU architecture.

**Comment by omemishra** [comment]
I have tried it dude but its not working ..... can i convert my arml8 to
arml7

**Comment by chrisk44** [comment]
No you can't change it, it's the hardware architecture of your device. Theoretically, I think, armv8l is backwards compatible with executables built for armv7l, but if your device can't run them then there is nothing I can do.

Don't take this the wrong way, but this app is not a toy or a pranking app, and one shouldn't use it if one doesn't understand even the basics of computers.

**Comment by omemishra** [comment]
I know dude ... m already using nethunter on my phone.... btw where u
from???

**Comment by chrisk44** [comment]
I'm from Greece. Since your device is incompatible I'm going to close the issue. If you manage to run the binaries on your device and still have a problem with the app, reopen it.

**Comment by omemishra** [comment]
okkk dude................
