### ISSUE TITLE
[Feature Request] HCXTools

### ISSUE THREAD

**Issue by JuniorJPDJ** [chrisk44/Hijacker#36]
You can add support of [HCXTools](https://github.com/ZerBea/hcxtools) to convert, import, dump and show info about cap files.
It gives you also posibility to upload your caps to online cracking service.

**Comment by chrisk44** [comment]
Apart from determining whether the cap file contains a handshake or not, Hijacker doesn't really care about the contents of it. Cracking the cap file on a phone or even tablet is a bad idea anyway, not enough computing power. This app's job is done after you have your cap file. So no reason to add extra stuff on it. The cap files are saved in an accessible directory so can do whatever you want with them.
Thanks for the suggestion anyway.

**Comment by JuniorJPDJ** [comment]
But if it contains handshake you can go 1 step forward and make it uploaded online, to cracking service
