### ISSUE TITLE
Beta Issues

### ISSUE THREAD

**Issue by NetviperZ** [chrisk44/Hijacker#4]
1- there is an error when checking Chroot directory (and yes my chroot directory is correct)
2-my external adapter ( TL-WN722N ) external adapter is no longer recognized in nethunter chroot after installing this version
3- device reboot  randomly when external adapter is plugged

**Comment by chrisk44** [comment]
1. When you say error when checking, you mean it fails the test or does the whole app crash?
2. Hijacker does not change anything in nethunter chroot.. It just chroots to kali, sets up the environment variables and runs reaver. If you didn't try reaver with pixie-dust, Hijacker didn't even touch kali. If there is a problem just try a reboot...

**Comment by NetviperZ** [comment]
yes the test fails, but my nexus5 keeps rebooting everytime I plug the my adapter and that is just happens with this version

**Comment by chrisk44** [comment]
wait, you mean that you installed the new version of Hijacker, and now everytime you plug in your adapter, the phone reboots?!

**Comment by NetviperZ** [comment]
exactly

**Comment by chrisk44** [comment]
this doesn't make sense... did you even run reaver with pixie-dust?

**Comment by NetviperZ** [comment]
The test failed, so this option has been disabled

**Comment by chrisk44** [comment]
Then I don't know what has happened with your adapter, but since the test failed, the app didn't use the chroot installation. Even if it succeded, you'd have to run reaver WITH pixie dust to use the chroot, otherwise it just uses the binary that comes with the app.

**Comment by NetviperZ** [comment]
In chroot reaver with pixie-dust worked well before with my external adapter, yes its really weird.. i will make a restore and see what's going on

**Comment by chrisk44** [comment]
That's good... About the test failing: The app checks if /data/local/nhsystem/kali-armhf directory exists, and boot_init in /system/bin. If one of these is missing, then it fails. Please check if these exist, and tell me. The binary might be somewhere else, I'll need to add it.

**Comment by NetviperZ** [comment]
i cheked before and yes /data/local/nhsystem/kali-armhf exists, however, in the /system/bin there is a file bootkali_init not boot_init

**Comment by chrisk44** [comment]
Yeah that's what I meant. I don't know why it fails, I will look into it. Does your adapter work?

**Comment by NetviperZ** [comment]
Of course I just tried it on my computer and it  works

**Comment by chrisk44** [comment]
i mean on the nexus...

**Comment by chrisk44** [comment]
By the way, what ROM are you running exactly?

**Comment by NetviperZ** [comment]
Not anymore.. i have to restore my phone first, i will do tomorrow since I work on it now, i just tried another adapter (AWUS036NH) and it works, once I pluggin again the first adapter the phone reboots

The ROM is a modified CM 14.1 (nougat) 
*Linux kali 3.4.0-cyanogenmod-g7ae20b3-dirty

**Comment by AutinDroid** [comment]
I am running the same ROM as @NetviperZ, and I also have Kali chroot failed on the tools test. My wifi card is the same as netviperz's, tested and working.

**Comment by chrisk44** [comment]
Yeah it doesn't detect the chroot directory for some reason... Actually, right now i'm wondering why it detects it on mine, rather than why it doesn't on nethunteros... I'll just install it...

**Comment by AutinDroid** [comment]
Anyways, I found a pixiewps binary for android (found here: https://github.com/aanarchyy/pixiewps-android). I don't know if it will work though.

**Comment by chrisk44** [comment]
pixiewps is an offline tool, what i need is the reaver 1.5.2 which has
pixie-dust integrated.

2016-12-03 2:48 GMT+02:00 AutinDroid <notifications@github.com>:

**Comment by AutinDroid** [comment]
Can we reopen this issue as chroot detection still doesn't work?

**Comment by chrisk44** [comment]
do you get directory or bootkali_init not found when you run the test?

**Comment by NetviperZ** [comment]
Indeed, chroot detection still doesn't work, i get " Chroot directory not found"

**Comment by NetviperZ** [comment]
@AutinDroid did your external adapter ( TL-WN722N ) works with this rom ?

**Comment by chrisk44** [comment]
Guys it works on my device with NetHunterOS...

**Comment by AutinDroid** [comment]
My Adapter works.

**Comment by AutinDroid** [comment]
I get directory not found. I would also like to report v.18 not responding upon start.

**Comment by chrisk44** [comment]
The app hangs when denied su permission, you need to go to settings and force close it, and then open the supersu app and remove the stored denial, so it will ask you again. As for the chroot directory, I can't figure out what is the problem, it detects it fine on my device both with NetHunterOS and CM 14.1 caf...

**Comment by AutinDroid** [comment]
SuperSu was not denied and I have tried multiple times.

**Comment by chrisk44** [comment]
busybox installed, removed and reinstalled the app?

**Comment by NetviperZ** [comment]
@AutinDroid I can't use my tp link because of this kernel panic or issue with the firmware maybe, What version exactly do you use ?
@chrisk44 I get also directory not found

**Comment by AutinDroid** [comment]
Maybe it's a problem with the stock firmware in NethunterOS. I use NethunterOS with the kali rolling full package, which may update the firmware (I'm not sure). I'm positive that it's a problem with the firmware or system, not Hijacker.

**Comment by AutinDroid** [comment]
I also forgot to mention that I had busybox installed (the one that busybox comes with) and have uninstalled and reinstalled multiple times.

**Comment by chrisk44** [comment]
I don't know, I installed NetHunterOS, nethunter zip, hijacker, ran nethunter app, run hijacker, it just worked.

**Comment by AutinDroid** [comment]
Just wondering, how does the app start chroot?

**Comment by chrisk44** [comment]
bootkali_init to ensure that kali is booted, then open a su shell and run:
chroot /data/local/nhsystem/kali-armhf /bin/bash -c '
export USER=root && 
export SHELL=/bin/bash && 
export MAIL=/var/mail/root && 
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin && 
export TERM=linux && 
export HOME=/root && 
export LOGNAME=root && 
export SHLVL=1 && 
export YOU_KNOW_WHAT=THIS_IS_KALI_LINUX_NETHUNER_FROM_JAVA_BINKY && 
monstart-nh && 
reaver -i wlan0 -vv -b 18:44:E6:C3:74:48 --channel 3 -d 1 -l 60 -K 1 '

as one command...

**Comment by NetviperZ** [comment]
Which nethunter zip did you installed? I followed this tuto https://gist.github.com/binkybear/8f0f4eee292d5263372f47c3c3edd08e

**Comment by AutinDroid** [comment]
I used the 11-26 kalifs full rolling package. I don't know about @chrisk44

**Comment by AutinDroid** [comment]
Ran the command and got "libsigchain.so from LD_PRELOAD cannot be preloaded (cannot open shared object file)"

**Comment by chrisk44** [comment]
Yes that's a problem with nethunter chroot and the reaver binary in it.. There's nothing I can do about this. I get that too, but it doesn't stop reaver from running... Obviously it doesn't work because i'm not on nethunteros but it starts and waits for a beacon.

**Comment by chrisk44** [comment]
About that not responding on start thing, is that still happening?

**Comment by AutinDroid** [comment]
The responding on start issue happens on v.18, v.19, v.19.2.

**Comment by AutinDroid** [comment]
I will try to install a different ROM (NethunterOS hammerhead, caf not included) and test the app.

**Comment by AutinDroid** [comment]
I think I have found the problem why v.19.2 isn't working. Apparently when I grant root access, the Hijacker UID is not granted root, nor is prompt for root. It cannot be found in SuperSu app.

**Comment by chrisk44** [comment]
The app never gets root itself, it just launches shells with root privileges and does whatever it needs to do using them.

**Comment by AutinDroid** [comment]
@netviperZ Do you have the app hanging issue?

**Comment by NetviperZ** [comment]
@AutinDroid  no not really, im using now the last CM 14.1 and its works just fine !

**Comment by AutinDroid** [comment]
I've installed the last NethunterOS and the hanging issue has stopped. I still have the chroot problem. @NetviperZ do you have no chroot detection?

**Comment by NetviperZ** [comment]
@AutinDroid Unfortunately no, there is a new more stable version of nethunteros? because it bugged all the time

**Comment by NetviperZ** [comment]
After having tested the last version, here are some remarks:

1 Manufacturer name for clients no longer appears as before (It worked well before v.18)
2 You have to enter the path of worldlist everytime time.. and also it will be preferable if the last handshake captured will be selected automatically
3 it will be very practical if we can sort APs by their security
4 adding a filter of WPS only  for quick attack via reaver will be cool 
5 No handshake recorded from airodump-ng

**Comment by chrisk44** [comment]
1. When you say it doesn't appear, you mean it says "Unknown manufacturer"? If yes, I changed something, let's see if it works for you.
2. Fixed, done.
3. You can filter them by security.
4. This would require changing a very basic part of the code, but I will do it at some point.
5. There are 2 ways to create .cap files. The first is to enable the option to capture every packet when airodump runs, which will result in cap-**.cap files rarely containing handshakes. The second is to try to crack a network password, in which case a file named handshake-**.cap (or wep_ivs-**.cap for wep) will be created, but there is no guarrantee that it will contain the handshake. Even if there happened to be a handshake while you were watching, it's not certain that you will capture it. Distance and signal strength are at play here, but more importantly, some networks are immune to this. I actually thought that this worked on every WPA/WPA2 network and I was going crazy when I implemented the cracking feature because it would never capture the handshake from my network. I realized that if the network used AES encryption, is would never capture the handshake, even if it was being conducted from my nexus itself, or my laptop right next to me. It worked as soon as I changed it to TKIP. Now, if you are trying to capture a handshake and Hijacker tells you that it got it and stops, but there is no handshake in the file, that's a problem. Keep me updated on this.

I have changed many parts of the code and implemented some more checks. I will upload a new version later today.

**Comment by NetviperZ** [comment]
AES encryption was the problem for handshake capture indeed, it worked after i changed it to TKIP, I also want to report that the new version v20 doesnt start at all, it crashes every time, i have uninstalled and reinstalled it multiple times and nothing happens.

**Comment by AutinDroid** [comment]
@netviperZ I have v.20 working, my only issue Chroot detection.

**Comment by chrisk44** [comment]
first of all, there is v1-beta.21... secondly, with clean install everything works for me...

**Comment by AutinDroid** [comment]
This is slightly off topic... but can somebody host the monstart-nh and monstop-nh scripts? I am using a different rom than nethunterOS and have compiled a kernel that should have chroot monitor mode capabilities on wlan0 (a flash-able zip kind of like the ones from the official nightlies).

**Comment by chrisk44** [comment]
This has nothing to do with Hijacker, though i think they are just scripts... just copy paste them from NethunterOS...

**Comment by AutinDroid** [comment]
Problem is, i don't have NethunterOS, and I dont have the time to flash it today.

**Comment by NetviperZ** [comment]
i also use a clean install of the last CM 14.1 caf and it still doesn't work with both version v.20 & v.21

**Comment by chrisk44** [comment]
busybox?

**Comment by NetviperZ** [comment]
SuperSu and busybox installed

**Comment by NetviperZ** [comment]
On other hand it works  well with v18

**Comment by NetviperZ** [comment]
Update: after i uninstalled and reinstalled busybox everything works !

**Comment by chrisk44** [comment]
For some reason the busybox installer sometimes doesn't actually install it.. I don't know why...

**Comment by NetviperZ** [comment]
I have done several tests to understand what really happens, everytime i install hijacker i have to reinstall busybox just after to replace some files, otherwise hijacker hangs to infinity

**Comment by chrisk44** [comment]
Hijacker doesn't change anything with busybox

**Comment by NetviperZ** [comment]
However after it replaces some old files everything works again

**Comment by chrisk44** [comment]
I'll just include busybox to get this over with....

**Comment by chrisk44** [comment]
I fixed that hanging issue without busybox, i'll restore my factory image to test on android 6 to see if I can fix that crashing issue, and I'll upload an update.

**Comment by NetviperZ** [comment]
I also have to report the little problem with SSID file path

**Comment by chrisk44** [comment]
in beacon flooding? what's wrong with it?

**Comment by NetviperZ** [comment]
add an android:text ..

**Comment by chrisk44** [comment]
i want the text to be a hint so you can just start writing without having to delete text... otherwise everytime you want beacon flooding you'd have to erase the text, or you'd get an error because the file is not found.

**Comment by NetviperZ** [comment]
The problem is that you must each time enter the same path, otherwise the path is not saved afer

**Comment by NetviperZ** [comment]
And The path could be ignored if it does not exist

**Comment by chrisk44** [comment]
i'll make it save the path until you close the app.

**Comment by NetviperZ** [comment]
Yeah that will be great !

**Comment by AutinDroid** [comment]
Good news! I have working Chroot detection! I have compiled a kernel that will work on nougat ROMs (not CM, but I can compile one for that) for the Nexus 5, with working wlan0 injection in Chroot. Right now I am creating the package, and I will start a pull request soon

**Comment by NetviperZ** [comment]
with v22?

**Comment by chrisk44** [comment]
Yes, the monstart-nh thing is my mistake, will fix it. About the kernel, does it fully support nethunter? what do you change in the kernel to make it compatible?

**Comment by AutinDroid** [comment]
Yes. I am finishing up the kernel right know, and you can be an early tester if you want to be.

**Comment by AutinDroid** [comment]
It fully supports nethunter. It's actually your kernel with the proper patches for wlan0 in chroot.

**Comment by chrisk44** [comment]
what patches?

**Comment by AutinDroid** [comment]
https://github.com/seemoo-lab/bcm-public/blob/90bed6e1c3ad70ddc23ccf44033b152e0db300b6/kernel_patches/40mhz_channels_5GHz.patch

**Comment by chrisk44** [comment]
just this patch and you have injection in chroot?

**Comment by AutinDroid** [comment]
Yes

**Comment by chrisk44** [comment]
nice, i'll patch it...

**Comment by AutinDroid** [comment]
You need to install nexutil, monstart-nh, libfakeioctlkali, and monstop-nh in /system/xbin 
Airodump-ng gives a kernel panic without the patch, while injection still works.

**Comment by chrisk44** [comment]
nvm, i won't touch this because it's for nethunter... but I may try yours...

**Comment by NetviperZ** [comment]
@AutinDroid did tools like pixie work properly with this patch ?

**Comment by AutinDroid** [comment]
I haven't checked, but airodump-ng causes a crash. I will try to find the reason.

**Comment by NetviperZ** [comment]
try with a different airodump binary

**Comment by AutinDroid** [comment]
In chroot

**Comment by AutinDroid** [comment]
I believe it's a problem with the kernel, and I am trying to get assistance from the nexmon devs.

**Comment by chrisk44** [comment]
I think that the kernel that comes with nethunteros has more tweeks than just one patch to support this. See if you can get that kernel and just use it on normal cm14.1caf....

**Comment by AutinDroid** [comment]
I want to make the kernel work on aosp, not caf or cm.

**Comment by chrisk44** [comment]
normal cm is based on aosp

**Comment by AutinDroid** [comment]
Good news! I got the kernel to work! I will upload the source and will need help with testing (pretty unstable).

**Comment by AutinDroid** [comment]
It has wlan0 Chroot injection working for AOSP based ROMs.

**Comment by AutinDroid** [comment]
Here is the package I have created: https://github.com/AutinDroid/HammerheadMon-Kernel/releases/tag/v0.1 
There may be a nightly release of it.
Also, please read the notes for further instructions.

**Comment by chrisk44** [comment]
Did you stop using the app or you just haven't found any bugs?

**Comment by AutinDroid** [comment]
So far no issues, and the app is working well so far. I forgot to test pixiewps though, I'll try that.

**Comment by AutinDroid** [comment]
On pixie-dust attacks, I get `ld.so: object 'libsigchain.so form LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored
/bin/bash: monstart-nh: No such file or directory`

**Comment by chrisk44** [comment]
I have already said that this is from the chroot environment... make sure you are running the latest version... what os are you on?

**Comment by AutinDroid** [comment]
I am using RC1 of the app, and my ROM is resurrection remix 5.80. Christ is from newest package.

**Comment by chrisk44** [comment]
like, jesus 2.0?

**Comment by AutinDroid** [comment]
lol 
I should really edit my dictionary so "Chroot" doesn't autocorrect into something religious.
I am using the latest chroot (not christ) available in the nethunter nightly pages.

**Comment by NetviperZ** [comment]
nothing to report, except the fact that airodump hangs during the first run after instalation just like previous versions, but after that the app works properly

**Comment by NetviperZ** [comment]
@AutinDroid whats your email ?

**Comment by AutinDroid** [comment]
Autintech@gmail.com

**Comment by chrisk44** [comment]
@AutinDroid how stable is your kernel?

**Comment by AutinDroid** [comment]
I'd say it's pretty stable, it your kernel with only two patches.

**Comment by chrisk44** [comment]
aosp or cm? and what patches?

**Comment by NetviperZ** [comment]
we waiting wps filter

**Comment by chrisk44** [comment]
you wait a bit longer...
