### ISSUE TITLE
Cracking .cap is too slow

### ISSUE THREAD

**Issue by dizcza** [chrisk44/Hijacker#40]
Running aircrack-ng in kali nethunter is much faster than in your app.
In kali, `aircrack-ng -S` outputs 460 k/s with Nexus 5 so a wordlist of 6772 passwords it processes in 15 seconds, while your app takes 2 min and 5 sec to finish (with stopped airodump). In case, if you don't know that.
Hijacker v1.5-beta.1
Kali Nethunter v3.15.4 (under probably your hammerheadcafcm kernel)
aircrack-ng v1.2 rc4

Updated.
I suppose, your app uses aircrack-ng, doesn't?

**Comment by chrisk44** [comment]
Try [this](https://github.com/chrisk44/Hijacker/files/1845323/Hijacker-release-v1.5-beta.2.zip).

**Comment by dizcza** [comment]
Now it works just as long as kali's aircrack-ng
same benchmark ~460 k/s
same cracking time 15 sec
Fixed.

**Comment by dizcza** [comment]
What do you think about adding top thousands most probably used digit passwords in your app? There can be a default wordlist like [here](https://drive.google.com/drive/folders/1G-ypDA_w_QuWdAYkevVy15dGRXpZEMsA?usp=sharing) (generated [here](https://gist.github.com/dizcza/42c78585d0c996de0054e8c8a9c84441)) or a user can choose its own. The reason for having this included is that you remove the burden from a user to collect a small set of publically used passwords. Since your app is run on Android devices only, I suppose no one uses a wordlist larger than 100k on their smartphones.

**Comment by chrisk44** [comment]
Yeah, maybe later... I don't want to include them in the package, but I could provide easy direct downloads from somewhere.

**Comment by dizcza** [comment]
Yes, autodownloaded rather than included in the binary.

Another issue I noticed is that after you start cracking .cap file, turn screen off and on, you don't see any result - whether the key is found or not.

**Comment by chrisk44** [comment]
You are right about the issue, I fixed it.

I noticed that the wordlist you linked above was generated by you. I added the download function to the app and the wordlists will be downloaded from the directory `wordlists` in the app's repo. Feel free to contribute by adding any good lists you may have.

**Comment by NetviperZ** [comment]
is't normal that all we see during bruteforcing procedure is "Running " ?

**Comment by chrisk44** [comment]
Yes.
