### ISSUE TITLE
Reaver bug

### ISSUE THREAD

**Issue by NetviperZ** [chrisk44/Hijacker#41]
When reaver associates with an AP, the internal WiFi stop monitoring and back to  work in normal mode, I am currently on marshmallow 6.0.1

**Comment by chrisk44** [comment]
That doesn't happen on my device, but I'm sure the app doesn't disable it. The app only runs the 'disable monitor mode' command when it exits.

**Comment by NetviperZ** [comment]
Nexus5 ?

**Comment by chrisk44** [comment]
Yes
