### ISSUE TITLE
REAVER ERROR 

### ISSUE THREAD

**Issue by arti2525** [chrisk44/Hijacker#43]
Hello I have the following error in reaver with nexus 6p
__nex_sriver_io: error
__nex_sriver_io: error
__nex_sriver_io: error
WARNING:Faild to associete 
when trying to attack the objective
THX

**Comment by chrisk44** [comment]
Did you install the firmware for your adapter to support monitor mode?

**Comment by arti2525** [comment]
yes ,
hello, if the tested the inside of hijaker.apk and the nexmon rebuild to the latest version, I get the same error

**Comment by arti2525** [comment]
in the beta4 not install firmware and management utility

**Comment by chrisk44** [comment]
I don't understand what you are saying. That error seems to me like a driver issue. Please make sure that the firmware is correctly installed and that the problem is within the app.

**Comment by arti2525** [comment]
hello I think I found the problem, when I launch reaver after a while the monitor mode falls and it gets up again, it's as if the monitor mode is reset, also when I put airodump to scan the wps and wep does not show them, but if the show with this command in the console
LD_PRELOAD=libfakeioctl.so airodump-ng -iwlan0
thx

**Comment by chrisk44** [comment]
Same answer as before.
