### ISSUE TITLE
Pixie wps doesn't work

### ISSUE THREAD

**Issue by dizcza** [chrisk44/Hijacker#45]
After I've upgraded kali nethunter, pixie wps stopped working. Before updating kali I still was not able to crack with pixie dust (I've run this attack only once and thought the problem was in the old reaver), but the output didn't contain error.
All tests in your app are passed OK.
Latest release v1.5-beta.5.
Nexus 5 hammerheadcm, built from your repo (Mar 4).
![screenshot from 2018-04-21 19-07-45](https://user-images.githubusercontent.com/7688337/39086344-b01ce4f4-4598-11e8-9a60-fb29da15b2a0.png)
![screenshot from 2018-04-21 19-08-04](https://user-images.githubusercontent.com/7688337/39086345-b03f23d4-4598-11e8-9958-341f541d0c62.png)
![screenshot from 2018-04-21 19-08-14](https://user-images.githubusercontent.com/7688337/39086346-b0624846-4598-11e8-96ba-96f51dfef447.png)

Side note. i't be nice to export reaver output log instead of APs and stations in the reaver menu export settings.

**Comment by chrisk44** [comment]
Unless you have NetHunter OS, the internal adapter in the NetHunter environment doesn't have monitor mode, so you need to have an external adapter with the correct firmware installed. If you don't, Reaver will run (at least that's what happens on my device), but you won't see any results. I don't know what happens with any NetHunter updates, though.

Now, about the error, this seems to be an issue in the NetHunter environment, so there is nothing I can do about it.

Exporting the reaver log (and any other console-like log, like cracking) is a good idea, and I will add it when I get a chance, along with the option to clear the output.

**Comment by dizcza** [comment]
I don't get it. I have NetHunter OS + Nexmon (from your app) and internal Broadcom BCM4339 chipset capable of switching in monitor mode through your app. Vanilla reaver (without pixie dust) with internal adapter works fine in Hijacker as well as airodump (that's why I use your app in the first place).
Since the error began appearing after I had updated Nethunter OS, it's probably a Nethunter OS bug. I thought you have experienced this behaviour in case if you update Nethunter OS on your phone. There is no reason to post this bug in kali Nethunter community - the use case is very specific.

**Comment by NetviperZ** [comment]
you guys probably dont discuss the same thing here
@dizcza: NetHunterOS here means a modified ROM of  NetHunter with working native monitor mode in the chroot using Nexmon.

**Comment by dizcza** [comment]
@NetviperZ how do i confirm that my NetHunter has working native monitor mode in the chroot?

**Comment by chrisk44** [comment]
You can test monitor mode by running the aircrack-ng test or just running airodump-ng IN the NetHunter environment. If monitor mode is enabled (`nexutil -m true`) then everything else should work too.
Additionally, there is a script that must run in the chroot environment to set up monitor mode, and Hijacker has the option to do that automatically. Find the option in settings.

**Comment by EvilAirborn** [comment]
No nethunteros not means nethunter with internal WiFi monitor mode,
example: I have oneplus one (bacon), it have an official nethunteros
build..yeah nethunteros..but it doesn't support monitor mode!

**Comment by dizcza** [comment]
When I copied "Reaver in chroot" test command and run it in chroot (I ran `nexutil -m true` beforehand) I did get the same error as I stated above. If I just enable monitor mode in chroot via nexutil and then run `airodump-ng wlan0` _in_ kali NetHunter terminal, I get
```
ioctl(SIOCSIWMODE) failed: Invalid argument
Error setting monitor mode on wlan0
```
where wlan0 is the internal adapter.
It's too much for me. I just stick to the basic usage.

**Comment by JuniorJPDJ** [comment]
If you want to make your nethunter work with nexmon, you need to compile libnexmon/libfakeioctl in chroot and preload it when using tools similar to that what you do on android.
I wasn't able to get libs working, I always get reboot.
Maybe someone will be able to do this.

**Comment by JuniorJPDJ** [comment]
https://github.com/seemoo-lab/nexmon/issues/211
There is progress in doing this thing

**Comment by EvilAirborn** [comment]
I was able to solve the issue and made the hijacker able to attack pixiewps nethunterless! It was successfully working on nexus 5,(hammerhead) but I don't know why, @chrisk44 rejected my update and told me that he will solve this on his own :)

**Comment by chrisk44** [comment]
@EvilAirborn I rejected your solution because it was not a solution. It was the equivilent of taking a car with failed brakes, attaching more airbags and calling it a day. You may survive, but that doesn't make it an acceptable solution.

**Comment by JuniorJPDJ** [comment]
@EvilAirborn show it here please

**Comment by ssofiian** [comment]
Hello

**Comment by ssofiian** [comment]
Can some one have rev/random/ for run pixie-dust in chroot with hijacker apk or link

**Comment by ssofiian** [comment]
Hello
