### ISSUE TITLE
fw_bcmdhd.bin not found

### ISSUE THREAD

**Issue by fnzv** [chrisk44/Hijacker#47]
Hello,
During the "Install Nexmon" i see this and i cannot properly install the driver.
Is there a workaround to upload it manually or install it separately?

**Comment by chrisk44** [comment]
This means that the app wasn't able to find the firmware location.

What device and OS are you using?

**Comment by fnzv** [comment]
I'm running the Oneplus One and CM12 5.1

**Comment by chrisk44** [comment]
Your device doesn't have the exact chipset for which the included firmware was written. Additionally, I haven't tested the firmware installation on such an old Android release.

There is a fw_bcmdhd.bin file somewhere in your system. This is the wifi firmware and needs to be replaced with the nexmon firmware.

Find the file, and run the command `strings /path/to/fw_bcmdhd.bin | grep \"FWID:\"`. This should give you the exact adapter name, which, for your device, might be 4339a0...
If it is, then you can manually replace that file with the nexmon firmware. You can find it in the repo, in the `assets` directory, file fw_bcmdhd_4339.bin (you will need to rename it to the original filename).

**Comment by Kashxk** [comment]
Hi. I have a Oneplus One too with LineageOS 14.1 and I'm having the same error: "fw_bcmdhd.bin not found". I tried to search for the file but didn't find any. I saw somewhere it said to check in /system/vendor/firmware and there's only one file there: "libpn547_fw.so".

Please help. Thank you.

**Comment by chrisk44** [comment]
The answer is above your post. If you can't find the file, I can't help you. I don't have a OnePlus One to find it myself.
