### ISSUE TITLE
ENHANCEMENT: Fluxion GUI (or something similar)

### ISSUE THREAD

**Issue by AutinDroid** [chrisk44/Hijacker#5]
I know that adding something like fluxion into the Hijacker app would be hard, but Fluxion is pretty useful in wifi-cracking. Fluxion runs properly in chroot, the only problem is that it is hard to use as it asks for the NetHunter GUI to be opened, which is not very convenient due to small text and input methods.

**Comment by chrisk44** [comment]
That's a tool that requires constant input and would be too difficult to implement in Hijacker for such a small gain. You can just open a shell in chroot and start it. It's already as easy as it gets...

**Comment by AutinDroid** [comment]
I guess it would be easier to run in a separate app than hijacker. It cannot be ran from the terminal app, which is the problem.

**Comment by chrisk44** [comment]
That's even worse.
