### ISSUE TITLE
Configurable LD_PRELOAD

### ISSUE THREAD

**Issue by cyrus104** [chrisk44/Hijacker#50]
Please enable LD_PRELOAD to be enabled at all times, maybe prepopulate it with a default of LD_PRELOAD=/path/to/libfakeioctl.so.

I am using Nexmon on an GS7 and am required to use LD_PRELOAD=/path/to/libnexmon.so instead of libfakeioctl.so.

This works for the version of airodump that Nexmon uses but I can't configure the custom LD_PRELOAD with Hijacker right now.

Thank you

**Comment by cyrus104** [comment]
Hey man, thanks for looking into this so quickly. I'll check in later on today when I am test a device with Nexmon. 

Thanks again!

**Comment by cyrus104** [comment]
This seems to have fixed the requested issue.

I understand the 32-bit vs 64-bit libnexmon.so has been reoccurring issues that has been opened/closed. All of the devices that I own right now, Samsung G7, Nexus 6P, and Huawei P9 are all 64-bit devices. I've tested the latest Hijacker release and the App-Release.zip but am not getting any love with the SG7 and Nexus 6P with a working version of Nexmon installed.

**Comment by chrisk44** [comment]
Well, if you have the 64bit versions of the libraries, you can try replacing the libs in `/data/data/com.hijacker/files/lib` with the 64bit ones.

**Comment by cyrus104** [comment]
Yeah, I tried that it's still not working.
herolte:/sdcard # LD_PRELOAD=/system/lib64/libnexmon.so /data/user/0/com.hijacker/files/bin/airodump-ng -i wlan0
CANNOT LINK EXECUTABLE "/data/user/0/com.hijacker/files/bin/airodump-ng": "/system/lib64/libnexmon.so" is 64-bit instead of 32-bit
Aborted
134|herolte:/sdcard #

Tried the 32-bit library.
herolte:/sdcard # LD_PRELOAD=/system/lib/libnexmon.so /data/user/0/com.hijacker/files/bin/airodump-ng -i wlan0
[0mCANNOT LINK EXECUTABLE "sh": "/system/lib/libnexmon.so" is 32-bit instead of 64-bit
CANNOT LINK EXECUTABLE "sh": "/system/lib/libnexmon.so" is 32-bit instead of 64-bit
CANNOT LINK EXECUTABLE "sh": "/system/lib/libnexmon.so" is 32-bit instead of 64-bit
CANNOT LINK EXECUTABLE "sh": "/system/lib/libnexmon.so" is 32-bit instead of 64-bit
CANNOT LINK EXECUTABLE "sh": "/system/lib/libnexmon.so" is 32-bit instead of 64-bit
CANNOT LINK EXECUTABLE "sh": "/system/lib/libnexmon.so" is 32-bit instead of 64-bit
[2J[?25l[2J
[2J[?25l[2J
CANNOT LINK EXECUTABLE "sh": "/system/lib/libnexmon.so" is 32-bit instead of 64-bit
[1;1H

**Comment by chrisk44** [comment]
Ah yeah, this is what was happening with all those closed issues, that's why I never figured it out, I don't even have a 64bit device to test it by myself.

**Comment by cyrus104** [comment]
It looks like airodump will pseudo launch only when /system/lib/libnexmon.so is specified but keeps throwing the errors above but you do get a few lines of the airodump commandline interface.

It doesn't even try to launch when lib64 is selected.

**Comment by chrisk44** [comment]
The airodump binary is 32bit, so a 32bit library should be used. The errors are different:
With the 64bit lib you get:
`CANNOT LINK EXECUTABLE "/data ... airodump-ng": lib is 64bit`
which is expected given that the binary is 32bit, but when you try the 32bit lib, you get:
`CANNOT LINK EXECUTABLE "sh": lib is 32-bit`
which kind of make sense because your `sh` binary is most likely 64bit (given that you are running a 64bit device), but I have never seen this and have no idea how to address it.

**Comment by cyrus104** [comment]
Understood, I've posted a couple of times on Nexmon board about it because their app has the same issue with devices that need the libnexmon.so. The app supports inject but currently won't use their libnexmon.so library, which makes me question why they created it or how they tested it.

The main benefit to using libnexmon.so is that it support radiotap headers and... injection!

**Comment by chrisk44** [comment]
This is not just about libnexmon, same thing happens with libfakeioctl. The problem here is that I don't have 64bit binaries for every tool my app uses. The weird thing is that some 64bit devices seem to work fine, given some bug reports I have received for unrelated issues.

**Comment by cyrus104** [comment]
Weirdly I check all of the binaries for the tools that Nexmon provides and they are the same as yours.

134|herolte:/sdcard # file airodump-ng
airodump-ng: ELF shared object, 32-bit LSB arm, dynamic (/system/bin/linker), stripped

herolte:/sdcard # file /system/bin/airodump-ng
/system/bin/airodump-ng: ELF shared object, 32-bit LSB arm, dynamic (/system/bin/linker), stripped

**Comment by chrisk44** [comment]
That's not weird, I used their source and instructions to compile the binaries. Unfortunately, I wasn't able to compile them for 64bit.

**Comment by cyrus104** [comment]
Right but those binaries are on my 64-bit device and they work.

herolte:/sdcard # LD_PRELOAD=/system/lib/libnexmon.so /system/bin/airodump-ng -i wlan0
^seems to work but not sure if inject would work as well.
