### ISSUE TITLE
[Feature request] use probable wordlists

### ISSUE THREAD

**Issue by dizcza** [chrisk44/Hijacker#55]
I noticed you've created `wordlist` directory filled with the famous rockyou.txt. I don't think anyone would try all 16M word candidates from rockyou using their smartphone CPU. A better approach is to take wordlists directly from https://github.com/berzerk0/Probable-Wordlists/tree/master/Real-Passwords. Benefits are:

* you don't need to have and maintain your own `wordlists` dir in the project
* those wordlists are statistically more probable than rockyou and are updated on a regular basis
* a user can choose how many word candidates he/she needs. I'd choose 'Top4800-WPA-probable-v2.txt' and 'Top204Thousand-WPA-probable-v2.txt' from `WPA-Length` folder

The filenames in Probable-Wordlists are not fixed (and can be changed at each commit) so you can either parse directory to show current filenames or download them in your 'wordlist' dir.

**Comment by chrisk44** [comment]
The `wordlists` directory is there for anyone to contribute. I can't have the app check anyone else's repo. You are more than welcome to add any wordlist you find useful.

**Comment by dizcza** [comment]
> I can't have the app check anyone else's repo

Got it.
