### ISSUE TITLE
fw_bcmdhd.bin not found

### ISSUE THREAD

**Issue by mirzaatifbaig** [chrisk44/Hijacker#56]
I am trying to install the nexmon firmware using Hijacker on Galaxy Note 3 running los 14.1 rooted with busybox.I have read that the Note 3 AOSP supports Monitor mode due to having the same chipset as Nexus 5 the bcm4339.So,When I try to install the patched firmware the application shows that it can't find the required binary file.So,How can I make it work.
Update:I have a Nexus 5 the app works well but the binary files have different locations and names.

**Comment by chrisk44** [comment]
[This](https://github.com/chrisk44/Hijacker/issues/47) literally has the exact same title as your post, and refers to exactly the same problem as yours.

**Comment by mirzaatifbaig** [comment]
He doesn't have the compatible chipset for which the firmware is but I do.It's the exact same Chipset as the Nexus 5

**Comment by chrisk44** [comment]
It's the same problem. Find the firmware file, what it's called and replace it yourself. Basically just install the new firmware on your device on your own. I have no idea how the files are named and where they are on these devices as I don't have any of them.

**Comment by mirzaatifbaig** [comment]
I got it working.Required a different ROM the AOSP 7.1.2 But the monitor mode is working flawlessly with Hijacker.All I wanted to know was which one of the 4 files was the firmware one turns out the bcmdhd_apsta.bin one is able to do it.Also I used the firmware from Nexmon 4339 renamed it and replaced it.Thanks anyway.

**Comment by numaphlex** [comment]
Yo! @mirzaatifbaig how you man? I was about to reach you to talk about this Hijacker i came across. This one works for me, no hassle, as @chrisk44 did all the dirty job already.

(also long reaching here, this dude @chrisk44 also has fingers in the Nethunter stuff, BTW the kernels...)

**Comment by mirzaatifbaig** [comment]
I am everywhere where the words monitor mode android is.It is a separate ID dedicated to this topic.I am developing some scripts to make nethunterOS on every frickin device with nexmon support.Ofcourse there are obstacles.Currently I am on 700+ errors but a dude of mine managed to boot one with note  3 with no touch,sound and sim card.I might release them on my real ID.Or show them the incinerator.Currently 10 people are working on the server.
