### ISSUE TITLE
mdk4 is available

### ISSUE THREAD

**Issue by kimocoder** [chrisk44/Hijacker#65]
This is just a notice about mdk4, a re-write of the good old mdk3 running on newer osdep, supports 2 adapters and fixes/bugfixes.

More information over at us here
https://github.com/aircrack-ng/mdk4

Great work you've done on this app. Works great.

**Comment by chrisk44** [comment]
I would need a compiled version that works on android to use it, but I'm not making this kind of updates to the app right now. My next step will most likely be a complete re-write of the app that will not use separate binaries for attacks, but this might prove useful.

Thanks for mentioning it though, good to know about it. Glad you like the app.
