### ISSUE TITLE
Issue with airodump

### ISSUE THREAD

**Issue by kimocoder** [chrisk44/Hijacker#66]
![screenshot_20190216-165251](https://user-images.githubusercontent.com/4252297/52905699-b2f5e800-320b-11e9-932e-f57925a93a67.png)

**Comment by chrisk44** [comment]
You make some good points...

**Comment by kimocoder** [comment]
Sorry, had some struggle finding the right device over here, so I figured.. an image would say it all?
"cannot link executable" it is :+1:

**Comment by chrisk44** [comment]
This is a known issue, if you look at the open issues you will find it. It's because you are trying to run 32bit binaries on a 64bit device, and there's trouble with the 32bit library that is linked with LD_PRELOAD. Haven't fixed it because I don't have a 64bit device.
