### ISSUE TITLE
Not working on android 9.0

### ISSUE THREAD

**Issue by SebiAi** [chrisk44/Hijacker#67]
## Current Behavior
Instant crash after opening. Can not see any menu.

## Expected Behavior
Should open without any problem.

## Detailed steps to reproduce the problem
1. Open app on android 9.0 device.

## Device details

* ROM: OxygenOS (9.5.5), Android: 9.0
* Other OS-related info: Stock. No root, no unlocked bootloader (I know it only works with root, but wanted to try anyway.)
* App version: Tried latest beta(Hijacker-release-v1.5-beta.8.apk) and latest stable(Hijacker-release-v1.4-stable.3.apk)
* Installed firmware: Nothing

## Suggested Solution
Most apps need a new permission to run in the forground: android.permission.FOREGROUND_SERVICE

#### By submitting this, I agree that:
* I am not a 13 year old who is trying to disconnect his friends from their wifi.
* I know what this app is supposed to do.
* I know what monitor-mode and a wifi adapter is, and what the firmware has to do with it.
* I have read the project's README and it didn't help.
* I don't speak 3rd grade english and my sentences make sense.

**Comment by necrose99** [comment]
Arm64 compiles for some builds might be required. As some use arm64 CPUs.

**Comment by chrisk44** [comment]
Sorry for the delay. The app has not been tested on Android 9 because I don't have a device for it. I have been getting a few bug reports from Android 9 devices regarding the app's startup. If I compile the app with the permission you are suggesting, could you test it?

**Comment by SebiAi** [comment]
> Sorry for the delay. The app has not been tested on Android 9 because I don't have a device for it. I have been getting a few bug reports from Android 9 devices regarding the app's startup. If I compile the app with the permission you are suggesting, could you test it?

Hey! Of course! I also have an Android 10 device if you need any further testing.

**Comment by chrisk44** [comment]
I just saw that your device is not rooted. This is going to be a problem, the app is going to crash because it can't open the su shell. Can you root it?

**Comment by SebiAi** [comment]
> I just saw that your device is not rooted. This is going to be a problem, the app is going to crash because it can't open the su shell. Can you root it?

Both my devices are rooted with Magisk.

**Comment by SebiAi** [comment]
Ok. Got the app currently running now. It told me that I might not be rooted because I don't use SuperSU (which is dead). And it can't auto install the nexmon firmware (see pictures). Do you need any further help with testing?

**Comment by SebiAi** [comment]
It seems like that my devices don't have a compatible wifi chipset to work with nexmon (according to the Github readme File).

**Comment by chrisk44** [comment]
If that's the case then you need to find the firmware and install it by yourself.
I'm glad the app starts correctly, I just made a few changes to better overcome some errors during startup, and to better search for the firmware file for already supported devices.

I will upload a new version later, but if your device doesn't have any of the 2 chipsets that the app currently supports by itself I'm afraid it won't be of any help to you.

If this issue is resolved you can go ahead and close it.
Thank you for your help.
