### ISSUE TITLE
Will this work on Samsung Note 3 SM-N900 (3g Exynos version) (update: not working on my SM-N900)

### ISSUE THREAD

**Issue by misaalanshori** [chrisk44/Hijacker#68]
I have the Samsung Note 3 SM-N900 (3g Exynos), its currently broken and I'm waiting for some parts to come. but I'm wondering if the chipset on this model works with Hijacker or not?

I can't check it on the phone because its broken and won't turn on and i also don't know what to search online to find it

**Comment by misaalanshori** [comment]
Nevermind, I found that its using Broadcom BCM4339 on this site: https://wikidevi.com/wiki/Samsung_Galaxy_Note_III_(SM-N900)

**Comment by misaalanshori** [comment]
Reopening because my sm-n900 might not be using the BCM4339 because on /system/vendor/firmware I found this
![Screenshot_20190803-085559](https://user-images.githubusercontent.com/38964181/62409818-87559700-b5cc-11e9-96aa-86ff08c8bdf2.png)
Does this mean that my phone have a BCM4335 chipset? If yes, is it possible to use Hijacker with this and how?

**Comment by mirzaatifbaig** [comment]
Dude, Just copy paste the pre-patched binaries and place the libfakeioctl into the spots, it should work.

**Comment by misaalanshori** [comment]
Im still not sure if i understand, but i dont have the time to think about this right now... Do i just copy the files for aircrack and stuff? What about the wifi firmware? I thought i need to have modified/patched nexmon firmwares?

**Comment by mirzaatifbaig** [comment]
> Im still not sure if i understand, but i dont have the time to think about this right now... Do i just copy the files for aircrack and stuff? What about the wifi firmware? I thought i need to have modified/patched nexmon firmwares?
.Then Patch it yourself, it's mostly just copy paste commands if you have the supported device and a good processor for compiling stuff.

**Comment by chrisk44** [comment]
The README clearly specifies which chipsets are supported. For anything other that those, you have to install the firmware by yourself. In this case, if your device's architecture is "armv7l" or "aarch64" the app will automatically install all the needed tools, otherwise you will have to find/compile them and install them manually. Instructions are available in the repo's README (look in the troubleshoot section).
