### ISSUE TITLE
How to start this app

### ISSUE THREAD

**Issue by darkr4y** [chrisk44/Hijacker#7]
Oneplus 3T wiht Kali Nethunter

When I test the stable release , it showed a black screen , and cannot do nothing...
I think we need make a guide and teach anybody how to run this app.

Thx

**Comment by AutinDroid** [comment]
@darkr4y Did you

**Comment by darkr4y** [comment]
Yep
If u want run Kali nethunter , U need install the SuperSu to get root first....

**Comment by darkr4y** [comment]
If u can tell me how to collect the log of this app , I can show u 

![image](https://cloud.githubusercontent.com/assets/4407382/23134396/a650428a-f7cf-11e6-8e17-8ff005abd509.png)

as u can see , I check the process list in my kali chroot env , it shows that Hijacker app is running 
cuz stats = R (TASK_RUNNING)
but I just got a black screen on my phone

**Comment by chrisk44** [comment]
If you granted root access to the app it should start without anything else. There is an issue when you deny root access that causes the app to freeze. No guide is required, the README should provide all the help you need.

Also, this app requires monitor mode to work. I don't think your device is currently capable of this.

**Comment by darkr4y** [comment]
if this app could support an external wifi adapter ?
I checked the SuperSu log , cuz there was no popup window ask me to confirm the root access ...
SuperSu shows that it need to be a pro version to get it work.
Now I can running this app thx a lot ... 


Now how to install the tools and Nexmon ?

**Comment by AutinDroid** [comment]
@darkr4y OP3 doesn't have nexmon support

**Comment by darkr4y** [comment]
I checked the url 
https://github.com/seemoo-lab/nexmon

got it ....
so sad ...

if u could use a kali chroot to get a external wifi adapter work , I think this app will be attention by more people ..
thx again :)

**Comment by chrisk44** [comment]
Hijacker can be used with an external adapter if you have a driver for android that supports monitor mode. If you have monitor mode in kali chroot via an external wifi adapter then you can use the app normally, as long as you set the interface name in settings and out it in monitor mode.

Now, about the app startup, I can't help you without a logcat. I have seen the app work on many devices so I don't think that a OnePlus device would have a problem. Uninstall it completely, install the latest v1.1 beta version (it's quite stable) and if it doesn't work, post here with a logcat with regex "HIJACKER".

**Comment by darkr4y** [comment]
I uninstalled the stable release and download the latest beta release.
When I open the settings , I find that the Prefix item is disabled.
So how can I change the cmd to chroot kali_fs ? in the stable release version , this option is enabled.
and I try to change the Chroot directory option , the app was crashed ..
Logcat showed stack trase:
File path can't be null

and I send a feedback to ur mail.

**Comment by darkr4y** [comment]
and I want to kow , when I use test tools function, how can I get the stdout or stderr ?
When I use this function , the app is also crashed.

**Comment by chrisk44** [comment]
Hijacker doesn't need the kali chroot environment to work. It is only required for the pixie-dust attack with Reaver. Since v1.1 all the tools and one library (the one that is preloaded with the command prefix) are included and installed in the app's private directory. That's why you don't have the option to change the prefix. This is only enabled when the device is not ARM so you need to manually install and configure the tools. Yours is ARM so you don't have to do anything.

I don't know about the crash. You have sent me 3 emails; 2 blanks and one with text, no report file. I can't help you without the report.

**Comment by darkr4y** [comment]
--------------------------------------------------------------------------------
Hijacker bug report - Tue Feb 21 10:34:55 GMT+08:00 2017

Android version: 23
Device: OnePlus ONEPLUS A3010
App version: v1.1-beta.1
App data path: /data/user/0/com.hijacker/files

Stack trace:
File path can't be null
com.hijacker.RootFile.<init>(RootFile.java:51)
com.hijacker.FileExplorerDialog.goToDirectory(FileExplorerDialog.java:126)
com.hijacker.FileExplorerDialog.onCreateDialog(FileExplorerDialog.java:117)
android.app.DialogFragment.getLayoutInflater(DialogFragment.java:407)
android.app.FragmentManagerImpl.moveToState(FragmentManager.java:973)
android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
android.app.BackStackRecord.run(BackStackRecord.java:793)
android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1540)
android.app.FragmentManagerImpl$1.run(FragmentManager.java:482)
android.os.Handler.handleCallback(Handler.java:739)
android.os.Handler.dispatchMessage(Handler.java:95)
android.os.Looper.loop(Looper.java:148)
android.app.ActivityThread.main(ActivityThread.java:5507)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

pref_file--------------------------------------
<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
    <boolean name="always_cap" value="false" />
    <string name="custom_chroot_cmd"></string>
    <string name="cap_dir">/sdcard/cap</string>
    <string name="chroot_dir">/data/local/nhsystem/kali-armhf</string>
    <string name="deauthWait">20</string>
    <int name="tools_version" value="2" />
    <string name="aireplay_dir">aireplay-ng -D</string>
    <string name="airodump_dir">airodump-ng</string>
    <boolean name="watchdog" value="true" />
    <boolean name="delete_extra" value="true" />
    <string name="aircrack_dir">aircrack-ng</string>
    <string name="enable_monMode">nexutil -m true</string>
    <boolean name="disclaimer" value="true" />
    <string name="disable_monMode">nexutil -m false</string>
    <boolean name="airOnStartup" value="false" />
    <boolean name="show_details" value="true" />
    <boolean name="target_deauth" value="false" />
    <string name="mdk3_dir">mdk3</string>
    <string name="iface">wlan1</string>
    <boolean name="debug" value="true" />
    <boolean name="monstart" value="true" />
    <boolean name="show_notif" value="true" />
    <string name="prefix">LD_PRELOAD=/vendor/lib/libfakeioctl.so</string>
    <boolean name="cont_on_fail" value="true" />
    <string name="reaver_dir">reaver</string>
</map>
app directory----------------------------------
fw_bcmdhd--------------------------------------
ps---------------------------------------------
busybox----------------------------------------
logcat-----------------------------------------

**Comment by darkr4y** [comment]
```

--------------------------------------------------------------------------------
Hijacker bug report - Tue Feb 21 10:39:32 GMT+08:00 2017

Android version: 23
Device: OnePlus ONEPLUS A3010
App version: v1.1-beta.1
App data path: /data/user/0/com.hijacker/files

Stack trace:
sush: is not how it should be
com.hijacker.RootFile.<init>(RootFile.java:88)
com.hijacker.TestDialog$1$6.run(TestDialog.java:197)
android.os.Handler.handleCallback(Handler.java:739)
android.os.Handler.dispatchMessage(Handler.java:95)
android.os.Looper.loop(Looper.java:148)
android.app.ActivityThread.main(ActivityThread.java:5507)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

pref_file--------------------------------------
<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
    <boolean name="always_cap" value="false" />
    <string name="custom_chroot_cmd"></string>
    <string name="cap_dir">/sdcard/cap</string>
    <string name="chroot_dir">/data/local/nhsystem/kali-armhf</string>
    <string name="deauthWait">20</string>
    <int name="tools_version" value="2" />
    <string name="aireplay_dir">aireplay-ng -D</string>
    <string name="airodump_dir">airodump-ng</string>
    <boolean name="watchdog" value="true" />
    <boolean name="delete_extra" value="true" />
    <string name="aircrack_dir">aircrack-ng</string>
    <string name="enable_monMode">nexutil -m true</string>
    <boolean name="disclaimer" value="true" />
    <string name="disable_monMode">nexutil -m false</string>
    <boolean name="airOnStartup" value="false" />
    <boolean name="show_details" value="true" />
    <boolean name="target_deauth" value="false" />
    <string name="mdk3_dir">mdk3</string>
    <string name="iface">wlan1</string>
    <boolean name="debug" value="true" />
    <boolean name="monstart" value="true" />
    <boolean name="show_notif" value="true" />
    <string name="prefix">LD_PRELOAD=/vendor/lib/libfakeioctl.so</string>
    <boolean name="cont_on_fail" value="true" />
    <string name="reaver_dir">reaver</string>
</map>
app directory----------------------------------
fw_bcmdhd--------------------------------------
ps---------------------------------------------
busybox----------------------------------------
logcat-----------------------------------------

```

**Comment by darkr4y** [comment]
I use AndroidSu terminal session to set wlan1 with monitor mode.
and Hijacker can scan ssid now , but it also show that "Airodump is not running" .
there is no busy box in the path:
/data/user/0/com.hijacker/files

**Comment by darkr4y** [comment]
I downloaded busybox from repo , and start wlan1 monitor mode manually.
Hijacker is working now.

but I change the value of enable monitor mode:
iwconfig wlan1 mode monitor

and replug the external wifi adpater , the app cannot auto start monitor mode.

If u can enhance the wifi chipset detection to auto set the value of 'enable monitor mode'  , thank u very much ...

**Comment by chrisk44** [comment]
I have a question for you. When you go to settings, do you have the option to install nexmon? And if not, what architecture does it say you have?

**Comment by chrisk44** [comment]
First of all, the app doesn't seem to have root access at all. Are you sure you have SuperSU installed and have granted su permissions to Hijacker?

**Comment by darkr4y** [comment]
![image](https://cloud.githubusercontent.com/assets/4407382/23160986/604541c0-f863-11e6-88ec-2e082424db79.png)

![image](https://cloud.githubusercontent.com/assets/4407382/23161015/7b268bfc-f863-11e6-862d-48e034abdb4f.png)

**Comment by chrisk44** [comment]
Ok try this:
Install the latest busybox using the busybox app, go to the directory you installed it (usually /su/xbin), copy the busybox binary, go to /data/data/com.hijacker/files/bin/ and replace the existing busybox file with the one you copied. Start the app and tell me if it worked.

**Comment by darkr4y** [comment]
plz see my last reply , I told u that:
```
I downloaded busybox from repo , and start wlan1 monitor mode manually.
Hijacker is working now.
```
I just put the busybox to /data/user/0/com.hijacker/files
and in my terminal I start wlan1 monitor mode manually.
then start the app , it worked.

now the problem is , if I skip the step about starting monitor mode manually , the app cannot set wlan1 monitor mode autoly.

**Comment by chrisk44** [comment]
Ok I found the problem. You can go to settings and set the "Enable monitor mode" and "Disable monitor mode" commands to automatically enable and disable monitor mode.

I will upload a new version in a few minutes.

**Comment by chrisk44** [comment]
I have sent you an email with a test version.

Uninstall Hijacker completely and install this test version. Report if it works without doing anything about busybox.

If it doesn't work, replace the busybox binary in /data/data/com.hijacker/files/bin/ with the one that the busybox app installs on your device and tell me if it works. If it does, send me the new busybox binary.

**Comment by darkr4y** [comment]
my architecture is armv7I ,nexmon cannot support it.
but change the value of "enable monitor mode"  from "nexutil -m true" to "iwconfig wlan1 mode monitor"
If I do not manually start the monitor mode, the app will not automatically open the monitor mode for me , so it cannot work.

**Comment by chrisk44** [comment]
Your architecture is aarch64, and your chipset is not supported anyway. I thought you had an external adapter.

**Comment by AutinDroid** [comment]
@darkr4y Have you tried to test monitor mode via command line?

**Comment by darkr4y** [comment]
@AutinDroid  Yep , I start wlan1 monitor mode via cli , the app can work.

@chrisk44  Yep, I hv a external wifi adapter , I already told u that = =.
and use the release from ur email , crash gone and test tools returns success.
![image](https://cloud.githubusercontent.com/assets/4407382/23163446/6b80983c-f86d-11e6-8e26-67f38424f716.png)


so the problem is the app cannot automatically start monitor mode now.

**Comment by chrisk44** [comment]
Alright, what exactly do you need to do to enable monitor mode?

**Comment by darkr4y** [comment]
@chrisk44 
first start the terminal emulator and select ANDROIDSU shell.
```
cd /data/user/0/com.hijacker/files/bin
./iwconfig wlan1 mode monitor
ifconfig wlan1 up
``` 
use this command to start the monitor mode manually,

I want the app to do this automatically

**Comment by chrisk44** [comment]
Put this in "Enable monitor mode":
/data/user/0/com.hijacker/files/bin/iwconfig wlan1 mode monitor; /data/user/0/com.hijacker/files/bin/ifconfig wlan1 up

**Comment by darkr4y** [comment]
so its just a problem about absolute path ... = =
and another suggestion:

if there would have a "Import options" function, to read the config from file like

[enable mode monitor] = "/data/user/0/com.hijacker/files/bin/iwconfig wlan1 mode monitor;/data/user/0/com.hijacker/files/bin/ifconfig wlan1 up"

or before do anything set the enviroment variable.

**Comment by chrisk44** [comment]
I don't understand what you need. The app offers you the options to run a command you specify to enable and disable monitor mode. You can also just write a small shell script and run it via those commands (like 'sh /sdcard/myscript.sh' so you can do whatever you want (although the app will not wait for the script to finish).

**Comment by darkr4y** [comment]
ooops I set up like u typed, but nothing happended. and after soon app crashed...
There is no judgment as to whether or not the success of the monitor mode is enabled.

and the app dont wait the command execution finished , and just start airodump , 
I did not read the source code, the implementation process is this way?

```

--------------------------------------------------------------------------------
Hijacker bug report - Tue Feb 21 19:55:18 GMT+08:00 2017

Android version: 23
Device: OnePlus ONEPLUS A3010
App version: v1.1-beta.2
App data path: /data/user/0/com.hijacker/files

Stack trace:
Unable to resume activity {com.hijacker/com.hijacker.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setBackgroundResource(int)' on a null object reference
android.app.ActivityThread.performResumeActivity(ActivityThread.java:3175)
android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3206)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1428)
android.os.Handler.dispatchMessage(Handler.java:102)
android.os.Looper.loop(Looper.java:148)
android.app.ActivityThread.main(ActivityThread.java:5507)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

pref_file--------------------------------------
<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
    <boolean name="always_cap" value="false" />
    <string name="custom_chroot_cmd"></string>
    <string name="deauthWait">20</string>
    <int name="tools_version" value="3" />
    <boolean name="watchdog" value="true" />
    <boolean name="delete_extra" value="true" />
    <string name="enable_monMode">/data/user/0/com.hijacker/files/bin/iwconfig wlan1 mode monitor;/data/user/0/com.hijacker/files/bin/ifconfig wlan1 up</string>
    <boolean name="disclaimer" value="true" />
    <string name="disable_monMode">nexutil -m false</string>
    <boolean name="airOnStartup" value="false" />
    <boolean name="show_details" value="true" />
    <string name="iface">wlan1</string>
    <boolean name="target_deauth" value="false" />
    <boolean name="debug" value="true" />
    <boolean name="monstart" value="true" />
    <boolean name="show_notif" value="true" />
    <string name="prefix">LD_PRELOAD=/vendor/lib/libfakeioctl.so</string>
    <boolean name="cont_on_fail" value="false" />
</map>
app directory----------------------------------
fw_bcmdhd--------------------------------------
ps---------------------------------------------
busybox----------------------------------------
logcat-----------------------------------------

```

**Comment by chrisk44** [comment]
I don't see a connection between this error and the previous problems. Does this happen without the custom command for monitor mode?

**Comment by darkr4y** [comment]
I change the "enable monitor mode" options , not the "custom command".
and I dont know what time the config will be saved , the second time I change the "enable monitor mode" options ,  app work = =.

**Comment by chrisk44** [comment]
That's what I mean, the "Enable monitor mode" command. The change is saved as soon as you click OK but that command is ran when the app starts and whenever airodump starts.

**Comment by darkr4y** [comment]
got it , i dont know why it will be crashed = = 

Finally can be happy to use the Hijacker.
thx ur open source code 👍
