### ISSUE TITLE
Please add support for armv8l

### ISSUE THREAD

**Issue by jlucaso1** [chrisk44/Hijacker#71]
I'm having trouble running on my Galaxy a10 armv8l device.

**Comment by chrisk44** [comment]
Try the latest version, beta.10, it should install and attempt to use the tools. I don't know if it'll work, give it a try.

**Comment by Thiviyan** [comment]
It's not working. Even after updating. Using Samsung j7 pro 2017.
All kali features working. I am using external wifi adapter and able to use wifite with my setup but. Hijacker not detecting any tools installed or working.
