### ISSUE TITLE
Hijacker to Magisk

### ISSUE THREAD

**Issue by CyberKid1987** [chrisk44/Hijacker#72]
Hijacker not working with magisk or participate working. can you fix it?

Χρηστο δοκιμασα την εφαρμογη σου απειρες φορες και μονο μια φορα πηρα αποτελεσματα. Εχω ενεργοποιησει και την επιλογη nethunter chroot μεσα απο τις ρυθμισεις αλλα ματαια. Μπορεις να βοηθησεις;

**Comment by chrisk44** [comment]
I did not understand... anything.

**Comment by CyberKid1987** [comment]
Αν χρησιμοποιεις για root το magisk η εφαρμογη σου δεν λειτουργει. Αναφερει οτι λειπει η εφαρμογη SuperSU και δεν ξεκιναει η αναζητηση δικτυων παρολο που εχω ενεργοποιησει το monitor mode μεσα απο το nethunter terminal Αν εχεις το χρονο και τη διαθεση μπορεις να το διορθωσεις;

Σε Samsing Galaxy Note 3 με SuperSU λειτουργουν ολα αψογα. Ευχαριστω!

**Comment by chrisk44** [comment]
This project is followed by hundreds of people, please write in english. If you click OK when the error appears the app should continue normally. It will try to run "su" and "su -c <command>" to run various tasks. If your root solution doesn't allow that then the app won't work and it will most likely crash, and won't even be able to provide a bug report.

**Comment by chrisk44** [comment]
You can try the latest release, v1.5-beta.11.

**Comment by CyberKid1987** [comment]
I found solution. Change interface wlan0 to wlan1mon. I try wlan1 and not working via magisk,

**Comment by chrisk44** [comment]
If this is resolved, please close the issue.

**Comment by CyberKid1987** [comment]
Working only release 1.4 stable.

**Comment by vinhjaxt** [comment]
I think the problem is that some Android devices don't have which command, so it will always fail to test su binary.

**Comment by vinhjaxt** [comment]
I manually patched to change "which su" to "su -v", and it works
