### ISSUE TITLE
wifi card cant connect router after i used the hijacker cant connect 

### ISSUE THREAD

**Issue by dragon-mma** [chrisk44/Hijacker#73]
after i used the hijacker my phone cant connect to any hotspot please hep 
thanks

**Comment by chrisk44** [comment]
Try turning the wifi off and on again.
If it doesn't work, try rebooting the device.
If it doesn't work:
Did you install nexmon through the app? Are you sure your device is supported by the app? Did you check "create backup"? If so, you can use the restore option from the app's settings to restore your firmware.

**Comment by dragon-mma** [comment]
the device is supported by the app.and i tryed evry thing .i  installed nexmon through the app.
my phone is xpria sony z3. app work smoothly. now broplem is wifi

**Comment by chrisk44** [comment]
Have you tried connecting to various wifi hotspots (not just one)? If you have restored the firmware through the app then you should have the firmware you had before you installed nexmon. If you did that and it still doesn't work, then I don't think the problem is caused by the app.

**Comment by dragon-mma** [comment]
i will try.thanks for respond
