### ISSUE TITLE
Crash on Android 10 on "Test Tools"

### ISSUE THREAD

**Issue by kimocoder** [chrisk44/Hijacker#76]
A logcat is provided with details.

------------------
No Channel found for pkg=com.hijacker, channelId=miscellaneous, id=0, tag=null, opPkg=com.hijacker, callingUid=10278, userId=0, incomingUserId=0, notificationUid=10278, notification=Notification(channel=miscellaneous pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x0 color=0xff0099cc actions=1 vis=PRIVATE)
------------------

[logcat_11-16-2019_07-52-55.txt](https://github.com/chrisk44/Hijacker/files/3853900/logcat_11-16-2019_07-52-55.txt)

**Comment by chrisk44** [comment]
I see no app crash on this logcat. If the app crashed, please submit the bug report through the app.

**Comment by kimocoder** [comment]
Found the error. Test Tools is LD_PRELOAD'ing libfakeioctl.so from /vendor/lib,
but there is no "libfakeioctl.so" or "libnexmon.so" there, tried to copy them over (even with mount -o remount,rw /vendor) but that doesn't work either.

**Comment by kimocoder** [comment]
Forced it over by editing in AS. Didn't work either, so i copied command and got a 32bit error as seen below

![Screenshot_20191220-213741](https://user-images.githubusercontent.com/4252297/71290828-1e9b6b00-2371-11ea-837d-edc212e8c950.jpg)
