### ISSUE TITLE
Kali Chroot not found

### ISSUE THREAD

**Issue by Lexus89** [chrisk44/Hijacker#8]
When i test all the tools all are fine (airodump mdk3 reaver) however Kali chroot check fails (bootkali_init not found). Chroot is installed correctly according to nethunter and changing the directory also doesn't help.

Not using nexmon but an external adapter

**Comment by chrisk44** [comment]
What ROM are you using?

**Comment by Lexus89** [comment]
Stock Nexus 5 hammerhead

**Comment by chrisk44** [comment]
Ok, I can see how this would happen. If the chroot environment is correctly installed, there should be a bootkali_init binary somewhere. Hijacker looks for it in /system/bin but it could very well be somewhere else. If you can locate it, I will fix it in the next release.

**Comment by chrisk44** [comment]
Actually, I'll make it look for the binary in every location that PATH points to.

**Comment by Lexus89** [comment]
hm weird, i can only find bootkali_init using AndroidSU terminal at /data/data/com.offsec.nethunter/... instead of /system/*.

i can find bootkali, bootkali_login and bootkali_bash in /system/bin though.

**Comment by chrisk44** [comment]
I'll look into it, maybe after some update nethunter installs the init binary in its private directory. I will make the app look for bootkali_bash. But I have to run bootkali_init anyway because the environment need to be initialized before it can be used. I'll see what I can do.

**Comment by chrisk44** [comment]
I checked and found that bootkali_init is always installed in /system/bin. Even if it's not there, it will be somewhere that PATH points to so that's what I implemented. I'm afraid you will have to reinstall your nethunter environment or maybe copy the bootkali_init binary you found somewhere that PATH points to so Hijacker will detect it.

**Comment by Lexus89** [comment]
@chrisk44 Thanks for checking! I was also looking and it seems now and then the symlinking to those files doesn't work correctly during install. Will reinstall the phone and see if things work. Really like the GUI, keep up the good work!
