### ISSUE TITLE
Lock channel 1

### ISSUE THREAD

**Issue by hoover2015** [chrisk44/Hijacker#80]
Based on v1.5-beta.11 test

OnePlus7+Android Pie 9.5.8 + Nethunter: When using Hijacker, the external wifi card is always locked on channel 1, Cannot scan other channels automatically. But wifite & airodump-ng are normal.

This problem does not exist on older Android version

**Comment by hoover2015** [comment]
I think this question may be more related to Aircrack-ng

**Comment by chrisk44** [comment]
I don't know exactly what may be at fault here, but the app is definitely not, as the app itself doesn't switch channels unless it's about focusing on a specific channel or executing am attack.

**Comment by kimocoder** [comment]
the aircrack-ng binaries should be updated
