### ISSUE TITLE
Nexmon: airodump-ng and other tools isn't working correctly

### ISSUE THREAD

**Issue by kimocoder** [chrisk44/Hijacker#81]
Phone: Samsung Galaxy S2 (i9100)
OS: CM13

Hijacker isn't working over here, but when I open a terminal and write "LD_PRELOAD=$path airodump-ng wlan0" it's working like a charm. Somethings wrong, somewhere..

![nexmon](https://user-images.githubusercontent.com/4252297/70878449-cdcaf180-1fc1-11ea-8da3-9929ab126884.jpg)

**Comment by chrisk44** [comment]
Please provide a logcat from the device and a more detailed description about "Hijacker isn't working".
