### ISSUE TITLE
Hi i have encountered an error:libfakeioctl.so is 32-bit instead of 64-bit

### ISSUE THREAD

**Issue by mmdlsu** [chrisk44/Hijacker#88]
Hello, I use Aireplay on Hijacker, but there is an error. I copied the test command, and the test reported an error. Can anyone help me solve it? May God bless you

**Comment by mmdlsu** [comment]
![Screenshot_20200327-185702](https://user-images.githubusercontent.com/57515771/77749407-f0f34b80-705c-11ea-9f10-97db7d5fd6d4.jpg)

**Comment by chrisk44** [comment]
There is a template for opening an issue which you should follow.
This error has already been discussed [here](https://github.com/chrisk44/Hijacker/issues/53).
