### ISSUE TITLE
Hi since only two chipsets are supported can i replace mine with one of them lets say it's S8.

### ISSUE THREAD

**Issue by minanagehsalalma** [chrisk44/Hijacker#89]

**Comment by chrisk44** [comment]
Any device that supports monitor mode should work with the app. If the app doesn't include the firmware, you can always install it by yourself.

**Comment by minanagehsalalma** [comment]
> Any device that supports monitor mode

@chrisk44 I don't think there is anyother than the two you mentioned.

And this wasn't my question.
