### ISSUE TITLE
Support for native monitor mode

### ISSUE THREAD

**Issue by Lyuu17** [chrisk44/Hijacker#95]
Repo: https://github.com/kimocoder/qualcomm_android_monitor_mode/blob/master/LIST_OF_DEVICES.txt

## Device details
* Xiaomi Mi A3 with MIUI CC9 port

#### By submitting this, I agree that:
* I am not a 13 year old who is trying to disconnect his friends from their wifi.
* I know what this app is supposed to do.
* I know what monitor-mode and a wifi adapter is, and what the firmware has to do with it.
* I have read the project's README and it didn't help.
* I don't speak 3rd grade english and my sentences make sense.

**Comment by chrisk44** [comment]
I'm already up to date on this, and it will eventually be available. Hijacker development has stopped, in favor of a complete rebuild that will provide out-of-the-box support for QCACLD devices.
