### ISSUE TITLE
not working with qualcomm_android_monitor_mode

### ISSUE THREAD

**Issue by straw1low** [chrisk44/Hijacker#98]
MI 8 Xiaomi.eu Miui 12.5 Using Qualcomm_android_Monitor_Mode. Introduced the interface and start command and stop monitor mode. The application simply hangs. And yes, I realize that this option does not support package injection

**Comment by r0m3767** [comment]
Not downloadable

**Comment by chrisk44** [comment]
This app has never supported the QCACLD wifi chipset. Please read the discontinuation notice in the README. The new app will support this chipset for monitor mode, as it is being developed and tested with a device that uses it. Package injection is still a long way to go though.

**Comment by azio7** [comment]
it works in my mix2s.
see #100
and there is a problem. see #101
